Attribute VB_Name = "Constants"
Public Const EVENTKEY_CREATED = 0
Public Const EVENTKEY_EDITED = 1
Public Const EVENTKEY_VIEWED = 2
Public Const EVENTKEY_REPRINTED = 3
Public Const EVENTKEY_FULFILLMENTSEND = 4
Public Const EVENTKEY_FULFILLMENTRESEND = 5
Public Const EVENTKEY_FULFILLMENTCANCEL = 6
Public Const EVENTKEY_SMS = 7
Public Const EVENTKEY_EMAIL = 8
Public Const EVENTKEY_RECATEGORISATION = 9
Public Const EVENTKEY_NOTAPPROVED = 10
Public Const EVENTKEY_APPROVED = 11
Public Const EVENTKEY_GEMINIPRINTED = 12


