//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.Fsd.Omiga.Web.Services.FindMortgageProductsWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://FindMortgageProducts.Omiga.vertex.co.uk")]
    public abstract class OmigaFindMortgageProducts : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.FindMortgageProducts.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.FindMortgageProducts.Omiga.vertex.co.uk")]
        public abstract RESPONSEType findMortgageProducts();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindMortgageProducts.Omiga.vertex.co.uk")]
    public class REQUESTType {
        
        /// <remarks/>
        public MORTGAGEPRODUCTREQUESTType MORTGAGEPRODUCTREQUEST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADMINSYSTEMSTATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OPERATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindMortgageProducts.Omiga.vertex.co.uk")]
    public class MORTGAGEPRODUCTREQUESTType {
        
        /// <remarks/>
        public string SEARCHCONTEXT;
        
        /// <remarks/>
        public string DISTRIBUTIONCHANNELID;
        
        /// <remarks/>
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        public string APPLICATIONFACTFINDNUMBER;
        
        /// <remarks/>
        public string MORTGAGESUBQUOTENUMBER;
        
        /// <remarks/>
        public string PURPOSEOFLOAN;
        
        /// <remarks/>
        public string TERMINYEARS;
        
        /// <remarks/>
        public string TERMINMONTHS;
        
        /// <remarks/>
        public string AMOUNTREQUESTED;
        
        /// <remarks/>
        public string LOANCOMPONENTAMOUNT;
        
        /// <remarks/>
        public string LTV;
        
        /// <remarks/>
        public string FLEXIBLEPRODUCTS;
        
        /// <remarks/>
        public string RECORDCOUNT;
        
        /// <remarks/>
        public string STARTRECORD;
        
        /// <remarks/>
        public string ALLPRODUCTSWITHOUTCHECKS;
        
        /// <remarks/>
        public string ALLPRODUCTSWITHCHECKS;
        
        /// <remarks/>
        public string PRODUCTSBYGROUP;
        
        /// <remarks/>
        public string PRODUCTGROUP;
        
        /// <remarks/>
        public string DISCOUNTEDPRODUCTS;
        
        /// <remarks/>
        public string DISCOUNTEDPERIOD;
        
        /// <remarks/>
        public string FIXEDRATEPRODUCTS;
        
        /// <remarks/>
        public string FIXEDRATEPERIOD;
        
        /// <remarks/>
        public string STANDARDVARIABLEPRODUCTS;
        
        /// <remarks/>
        public string CAPPEDFLOOREDPRODUCTS;
        
        /// <remarks/>
        public string CAPPEDFLOOREDPERIOD;
        
        /// <remarks/>
        public string MORTGAGEPRODUCTCODE;
        
        /// <remarks/>
        public string MANUALPORTEDLOANIND;
        
        /// <remarks/>
        public int NATUREOFLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NATUREOFLOANSpecified;
        
        /// <remarks/>
        public int CREDITSCHEME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREDITSCHEMESpecified;
        
        /// <remarks/>
        public int GUARANTORIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GUARANTORINDSpecified;
        
        /// <remarks/>
        public int INCOMESTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCOMESTATUSSpecified;
        
        /// <remarks/>
        public int FLEXIBLEIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FLEXIBLEINDSpecified;
        
        /// <remarks/>
        public int MAXRECORDS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MAXRECORDSSpecified;
        
        /// <remarks/>
        public string DATABASEVERSION;
        
        /// <remarks/>
        public string COUNTRYOFORIGIN;
        
        /// <remarks/>
        public string LANGUAGE;
        
        /// <remarks/>
        public int TYPEOFAPPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TYPEOFAPPLICATIONSpecified;
        
        /// <remarks/>
        public int REPAYMENTMETHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTMETHODSpecified;
        
        /// <remarks/>
        public System.Single INTERESTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTONLYELEMENTSpecified;
        
        /// <remarks/>
        public System.Single CAPITALANDINTERESTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPITALANDINTERESTELEMENTSpecified;
        
        /// <remarks/>
        public int EMPLOYMENTSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMPLOYMENTSTATUSSpecified;
        
        /// <remarks/>
        public string LENDERID;
        
        /// <remarks/>
        public int CASHBACKPRODUCTS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CASHBACKPRODUCTSSpecified;
        
        /// <remarks/>
        public int IMPAIREDCREDITRATING;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IMPAIREDCREDITRATINGSpecified;
        
        /// <remarks/>
        public int MEMBEROFSTAFF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MEMBEROFSTAFFSpecified;
        
        /// <remarks/>
        public int EXISTINGCUSTOMER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EXISTINGCUSTOMERSpecified;
        
        /// <remarks/>
        public int TYPEOFBUYER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TYPEOFBUYERSpecified;
        
        /// <remarks/>
        public string EMPLOYMENTSTATUSLIST;
        
        /// <remarks/>
        public string ORDERBY;
        
        /// <remarks/>
        public string TAGNAME;
        
        /// <remarks/>
        public int MAXAGE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MAXAGESpecified;
        
        /// <remarks/>
        public int MINAGE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MINAGESpecified;
        
        /// <remarks/>
        public string APP1DOB;
        
        /// <remarks/>
        public string APP2DOB;
        
        /// <remarks/>
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        public string ARFIRMID;
        
        /// <remarks/>
        public string PACKAGERID;
        
        /// <remarks/>
        public string MORTGAGECLUBID;
        
        /// <remarks/>
        public string PACKAGERASSOCIATIONID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLPARAMType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DIRECTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLCOMMANDType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SQLPARAM")]
        public SQLPARAMType[] SQLPARAM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMMANDTEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public SQLCOMMANDType SQLCOMMAND;
        
        /// <remarks/>
        public string COMPONENT_ID;
        
        /// <remarks/>
        public string COMPONENT_RESPONSE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindMortgageProducts.Omiga.vertex.co.uk")]
    public class MORTGAGEPRODUCTType {
        
        /// <remarks/>
        public string MORTGAGEPRODUCTCODE;
        
        /// <remarks/>
        public string STARTDATE;
        
        /// <remarks/>
        public string PRODUCTNAME;
        
        /// <remarks/>
        public string PRODUCTTEXTDETAILS;
        
        /// <remarks/>
        public string LENDERSNAME;
        
        /// <remarks/>
        public string FIRSTMONTHSREPAYMENT;
        
        /// <remarks/>
        public string FIRSTMONTHSREPAYMENTBYDAILY;
        
        /// <remarks/>
        public string FIRSTMONTHLYINTERESTRATE;
        
        /// <remarks/>
        public string DISCOUNTEDPERIOD;
        
        /// <remarks/>
        public string TYPE;
        
        /// <remarks/>
        public string DISCOUNTAMOUNT;
        
        /// <remarks/>
        public string FIRSTMONTHLYSVRREPAYMENT;
        
        /// <remarks/>
        public string FIRSTMONTHLYSVRREPAYBYDAILY;
        
        /// <remarks/>
        public string FEE;
        
        /// <remarks/>
        public string PENALTIES;
        
        /// <remarks/>
        public string FLEXIBLEMORTGAGEPRODUCT;
        
        /// <remarks/>
        public string NONPANELLENDEROPTION;
        
        /// <remarks/>
        public string INTERESTRATEENDDATE;
        
        /// <remarks/>
        public string INTERESTRATEPERIOD;
        
        /// <remarks/>
        public string TYPICALAPR;
        
        /// <remarks/>
        public string ORGANISATIONID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindMortgageProducts.Omiga.vertex.co.uk")]
    public class MORTGAGEPRODUCTLISTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MORTGAGEPRODUCT")]
        public MORTGAGEPRODUCTType[] MORTGAGEPRODUCT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TOTAL;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindMortgageProducts.Omiga.vertex.co.uk")]
    public class RESPONSEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MORTGAGEPRODUCTLIST")]
        public MORTGAGEPRODUCTLISTType[] MORTGAGEPRODUCTLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
