Attribute VB_Name = "ErrorConstants"
'TW     18/10/2005  MAR223
Option Explicit
Public Enum ERRORS
    oeUnspecifiedError
    eNOTMIPLEMENTED = vbObjectError + 512
    eXMLMISSINGELEMENT
    eXMLMISSINGATTRIBUTE
    eXMLINVALIDATTTRIBUTE
    eXMLINVALIDATTTRIBUTEVALUE
    eRECORDNOTFOUND
    eUNSPECIFIEDERROR = vbObjectError + 512 + 999
    eINVALIDCUSTOMERROLE
    eNOADDRESS
    eINVALIDPARAMETER
    eINVALIDDATETIMEFORMAT
    eFAILEDTOLOADREQUEST = vbObjectError + 512 + 1
End Enum
