VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IRiskAssessmentTxBO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function CreateRuleOverride(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function

Public Function UpdateRAUnderwriterDecision(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function

Public Sub StoreRiskAssResults( _
    ByVal vobjXmlRequest As IXMLDOMNode, _
    ByVal vobjXmlResponse As IXMLDOMNode)

End Sub



