//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.FSD.Omiga.Web.Services.GetNextMessageSequenceNumberWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com")]
    public abstract class GetNextSequenceNumber : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com")]
        public abstract RESPONSEType getNextMessageSequenceNumber();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com")]
    public class REQUESTType {
        
        /// <remarks/>
        public INTERFACEType INTERFACE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com")]
    public class INTERFACEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("FirstTitleOutbound")]
        public string NAME = "FirstTitleOutbound";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public string SQLCOMMAND;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetNextMessageSequenceNumber.IDUK.Omiga.marlboroughstirling.com")]
    public class RESPONSEType {

/*        
		//	ik_mars894_20051215
        /// <remarks/>
        public long MESSAGESEQUENCENUMBER;
*/		
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
