//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// History
// HMA  21/05/2006	MAR1820 Set Keep Alive = False
// PSC	26/05/2006	MAR1820	Change to set HTTP protocol version to 1.0
//
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Vertex.Fsd.Omiga.omFDM.WebRefFileNet 
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using System.Net;
	using System.Reflection;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FNCEWS10SoapBinding", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/SOAP/wsdl")]
    public class FNCEWS10ServiceWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
		// MAR1820
		private static PropertyInfo requestPropertyInfo = null; 

		protected override System.Net.WebRequest GetWebRequest(Uri uri) 
		{ 
			WebRequest request = base.GetWebRequest(uri); 

			if (requestPropertyInfo==null) 
				// Retrieve property info and store it in a static member for optimizing future use 
				requestPropertyInfo = request.GetType().GetProperty("Request"); 

			// Retrieve underlying web request 
			HttpWebRequest webRequest = 
				(HttpWebRequest)requestPropertyInfo.GetValue(request,null); 

			// Setting HTTP Protocol Version to Version 1.0 
			webRequest.ProtocolVersion = System.Net.HttpVersion.Version10;
			return request; 
		} 

        public Localization LocalizationValue;
        
        /// <remarks/>
        public FNCEWS10ServiceWse() {
            this.Url = "http://localhost:6070/FNCEWS10SOAP/";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#GetObjects", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetObjectsResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ObjectResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)]
        public ObjectResponseType[] GetObjects([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] [System.Xml.Serialization.XmlArrayItemAttribute("ObjectRequest", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)] ObjectRequestType[] GetObjectsRequest) {
            object[] results = this.Invoke("GetObjects", new object[] {
                        GetObjectsRequest});
            return ((ObjectResponseType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetObjects(ObjectRequestType[] GetObjectsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetObjects", new object[] {
                        GetObjectsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ObjectResponseType[] EndGetObjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObjectResponseType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#ExecuteChanges", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ExecuteChangesResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ChangeResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)]
        public ChangeResponseType[] ExecuteChanges([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] ExecuteChangesRequest ExecuteChangesRequest) {
            object[] results = this.Invoke("ExecuteChanges", new object[] {
                        ExecuteChangesRequest});
            return ((ChangeResponseType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteChanges(ExecuteChangesRequest ExecuteChangesRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteChanges", new object[] {
                        ExecuteChangesRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChangeResponseType[] EndExecuteChanges(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChangeResponseType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#ExecuteSearch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ExecuteSearchResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        public ObjectSetType ExecuteSearch([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] SearchRequestType ExecuteSearchRequest) {
            object[] results = this.Invoke("ExecuteSearch", new object[] {
                        ExecuteSearchRequest});
            return ((ObjectSetType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteSearch(SearchRequestType ExecuteSearchRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteSearch", new object[] {
                        ExecuteSearchRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ObjectSetType EndExecuteSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObjectSetType)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#GetSearchMetadata", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSearchMetadataResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        public GetSearchMetadataResponse GetSearchMetadata([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] GetSearchMetadataRequest GetSearchMetadataRequest) {
            object[] results = this.Invoke("GetSearchMetadata", new object[] {
                        GetSearchMetadataRequest});
            return ((GetSearchMetadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSearchMetadata(GetSearchMetadataRequest GetSearchMetadataRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSearchMetadata", new object[] {
                        GetSearchMetadataRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetSearchMetadataResponse EndGetSearchMetadata(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetSearchMetadataResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FNCEWS10SoapBinding", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/SOAP/wsdl")]
    public class FNCEWS10Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public Localization LocalizationValue;
        
        /// <remarks/>
        public FNCEWS10Service() {
            this.Url = "http://localhost:6070/FNCEWS10SOAP/";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#GetObjects", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetObjectsResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ObjectResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)]
        public ObjectResponseType[] GetObjects([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] [System.Xml.Serialization.XmlArrayItemAttribute("ObjectRequest", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)] ObjectRequestType[] GetObjectsRequest) {
            object[] results = this.Invoke("GetObjects", new object[] {
                        GetObjectsRequest});
            return ((ObjectResponseType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetObjects(ObjectRequestType[] GetObjectsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetObjects", new object[] {
                        GetObjectsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ObjectResponseType[] EndGetObjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObjectResponseType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#ExecuteChanges", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ExecuteChangesResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ChangeResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)]
        public ChangeResponseType[] ExecuteChanges([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] ExecuteChangesRequest ExecuteChangesRequest) {
            object[] results = this.Invoke("ExecuteChanges", new object[] {
                        ExecuteChangesRequest});
            return ((ChangeResponseType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteChanges(ExecuteChangesRequest ExecuteChangesRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteChanges", new object[] {
                        ExecuteChangesRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChangeResponseType[] EndExecuteChanges(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChangeResponseType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#ExecuteSearch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ExecuteSearchResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        public ObjectSetType ExecuteSearch([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] SearchRequestType ExecuteSearchRequest) {
            object[] results = this.Invoke("ExecuteSearch", new object[] {
                        ExecuteSearchRequest});
            return ((ObjectSetType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteSearch(SearchRequestType ExecuteSearchRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteSearch", new object[] {
                        ExecuteSearchRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ObjectSetType EndExecuteSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObjectSetType)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LocalizationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.filenet.com/ns/fnce/2004/06/ws/SOAP#GetSearchMetadata", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSearchMetadataResponse", Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
        public GetSearchMetadataResponse GetSearchMetadata([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")] GetSearchMetadataRequest GetSearchMetadataRequest) {
            object[] results = this.Invoke("GetSearchMetadata", new object[] {
                        GetSearchMetadataRequest});
            return ((GetSearchMetadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSearchMetadata(GetSearchMetadataRequest GetSearchMetadataRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSearchMetadata", new object[] {
                        GetSearchMetadataRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetSearchMetadataResponse EndGetSearchMetadata(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetSearchMetadataResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema", IsNullable=false)]
    public class Localization : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Locale;
        
        /// <remarks/>
        public string Timezone;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class GetSearchMetadataRequest {
        
        /// <remarks/>
        public SearchScopeType SearchScope;
        
        /// <remarks/>
        public string ClassFilter;
        
        /// <remarks/>
        public PropertyFilterType PropertyFilter;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MergedScope))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectStoreScope))]
    public abstract class SearchScopeType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class MergedScope : SearchScopeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComponentScope")]
        public SearchScopeType[] ComponentScope;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MergedScopeMergeMode mergeMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mergeModeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum MergedScopeMergeMode {
        
        /// <remarks/>
        Union,
        
        /// <remarks/>
        Intersection,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ObjectStoreScope : SearchScopeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objectStore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class PropertyFilterType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncludeProperties")]
        public FilterElementType[] IncludeProperties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncludeTypes")]
        public FilterElementType[] IncludeTypes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludeProperties")]
        public string[] ExcludeProperties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxRecursion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxRecursionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.UInt64 maxSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSizeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxElements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxElementsSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class FilterElementType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxRecursion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxRecursionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.UInt64 maxSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSizeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxElements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxElementsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoredSearch))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrincipalSearch))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RepositorySearch))]
    public abstract class SearchRequestType {
        
        /// <remarks/>
        public PropertyFilterType SelectionFilter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxElements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxElementsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string continueFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool continuable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool continuableSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class StoredSearch : SearchRequestType {
        
        /// <remarks/>
        public ObjectReference SearchObject;
        
        /// <remarks/>
        public System.Xml.XmlElement ExecuteXML;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RepositorySearchModeType repositorySearchMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool repositorySearchModeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectSpecification))]
    public class ObjectReference : WithObjectIdentityType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetrievalError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectSpecification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DependentObjectType))]
    public abstract class WithObjectIdentityType : ObjectEntryType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objectId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objectStore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Unevaluated))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WithObjectIdentityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetrievalError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectSpecification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DependentObjectType))]
    public abstract class ObjectEntryType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class Unevaluated : ObjectEntryType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class RetrievalError : WithObjectIdentityType {
        
        /// <remarks/>
        public ErrorStackType ErrorStack;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ErrorStackType {
        
        /// <remarks/>
        public ErrorNameType ErrorName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorRecord")]
        public ErrorRecordType[] ErrorRecord;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum ErrorNameType {
        
        /// <remarks/>
        SERVER_ERROR,
        
        /// <remarks/>
        HEAP_FAILURE,
        
        /// <remarks/>
        DEADLOCK_ERROR,
        
        /// <remarks/>
        DATABASE_ERROR,
        
        /// <remarks/>
        DATABASE_FULL,
        
        /// <remarks/>
        TRANSACTION_TIMEOUT,
        
        /// <remarks/>
        AUTHENTICATION_FAILURE,
        
        /// <remarks/>
        NOT_SUPPORTED,
        
        /// <remarks/>
        BAD_CLASSID,
        
        /// <remarks/>
        BAD_PROPERTYID,
        
        /// <remarks/>
        BAD_INDEX,
        
        /// <remarks/>
        BAD_OBJECT,
        
        /// <remarks/>
        INVALID_REQUEST,
        
        /// <remarks/>
        REQUIRED_VALUE_ABSENT,
        
        /// <remarks/>
        OBJECT_NOT_FOUND,
        
        /// <remarks/>
        OBJECT_DELETED,
        
        /// <remarks/>
        BAD_VALUE,
        
        /// <remarks/>
        DATATYPE_MISMATCH,
        
        /// <remarks/>
        ACCESS_DENIED,
        
        /// <remarks/>
        CONSTRAINT_VIOLATED,
        
        /// <remarks/>
        NOT_UNIQUE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ErrorRecordType {
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diagnostic")]
        public DiagnosticType[] Diagnostic;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class DiagnosticType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string diagnosticType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DependentObjectType))]
    public class ObjectValue : WithObjectIdentityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public PropertyType[] Property;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int updateSequenceNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateSequenceNumberSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int accessAllowed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessAllowedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] superClasses;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumOfObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModifiablePropertyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfInteger32))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfFloat64))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfBinary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfBoolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonInteger32))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonFloat64))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonBinary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonBoolean))]
    public abstract class PropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string propertyId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool settable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settableSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class EnumOfObject : PropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public ObjectValue[] Value;
        
        /// <remarks/>
        public CollectionTerminatorType CollectionTerminator;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TraversalError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndOfPage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndOfCollection))]
    public abstract class CollectionTerminatorType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class TraversalError : CollectionTerminatorType {
        
        /// <remarks/>
        public ErrorStackType ErrorStack;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class EndOfPage : CollectionTerminatorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string continueFrom;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class EndOfCollection : CollectionTerminatorType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfInteger32))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfFloat64))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfBinary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOfBoolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonInteger32))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonId))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonFloat64))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonDateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonBinary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingletonBoolean))]
    public abstract class ModifiablePropertyType : PropertyType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ContentData : ModifiablePropertyType {
        
        /// <remarks/>
        public ContentType Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InlineContent))]
    public abstract class ContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.UInt64 size;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class InlineContent : ContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] Binary;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfString : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfObject : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public DependentObjectType[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class DependentObjectType : ObjectValue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int originalIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalIndexSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int newIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newIndexSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DependentObjectTypeDependentAction dependentAction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dependentActionSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum DependentObjectTypeDependentAction {
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Move,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfInteger32 : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public int[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfId : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfFloat64 : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public System.Double[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfDateTime : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public System.DateTime[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfBinary : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="base64Binary")]
        public System.Byte[][] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ListOfBoolean : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public bool[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonString : ModifiablePropertyType {
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonObject : ModifiablePropertyType {
        
        /// <remarks/>
        public ObjectEntryType Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonInteger32 : ModifiablePropertyType {
        
        /// <remarks/>
        public int Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonId : ModifiablePropertyType {
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonFloat64 : ModifiablePropertyType {
        
        /// <remarks/>
        public System.Double Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonDateTime : ModifiablePropertyType {
        
        /// <remarks/>
        public System.DateTime Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonBinary : ModifiablePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class SingletonBoolean : ModifiablePropertyType {
        
        /// <remarks/>
        public bool Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ChangeResponseType : ObjectValue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ObjectSpecification : ObjectReference {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string propertyId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int itemIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemIndexSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string batchRef;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum RepositorySearchModeType {
        
        /// <remarks/>
        Rows,
        
        /// <remarks/>
        Objects,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class PrincipalSearch : SearchRequestType {
        
        /// <remarks/>
        public string SearchRealm;
        
        /// <remarks/>
        public string SearchPattern;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool includeUsers;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeUsersSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool includeGroups;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeGroupsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrincipalSearchPrincipalSearchType principalSearchType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool principalSearchTypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrincipalSearchPrincipalSearchAttribute principalSearchAttribute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool principalSearchAttributeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrincipalSearchPrincipalSort principalSort;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool principalSortSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum PrincipalSearchPrincipalSearchType {
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        PrefixMatch,
        
        /// <remarks/>
        SuffixMatch,
        
        /// <remarks/>
        Contains,
        
        /// <remarks/>
        Exact,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum PrincipalSearchPrincipalSearchAttribute {
        
        /// <remarks/>
        ShortName,
        
        /// <remarks/>
        DisplayName,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum PrincipalSearchPrincipalSort {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class RepositorySearch : SearchRequestType {
        
        /// <remarks/>
        public SearchScopeType SearchScope;
        
        /// <remarks/>
        public string SearchSQL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RepositorySearchModeType repositorySearchMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool repositorySearchModeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstallAddOnAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RaiseEventAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplySecurityTemplateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DemoteVersionAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PromoteVersionAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnlockAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LockAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveContentAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeClassAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeStateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FreezeAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckinAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckoutAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateAction))]
    public abstract class ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class InstallAddOnAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addOnId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class RaiseEventAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public ModifiablePropertyType[] EventProperties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ApplySecurityTemplateAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applyStateId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class DemoteVersionAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class PromoteVersionAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class UnlockAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class LockAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.UInt32 timeout;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class MoveContentAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetPolicyId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool moveAllVersions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moveAllVersionsSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ChangeClassAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string newClass;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ChangeStateAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChangeStateActionLifecycleAction lifecycleAction;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum ChangeStateActionLifecycleAction {
        
        /// <remarks/>
        Reset,
        
        /// <remarks/>
        Promote,
        
        /// <remarks/>
        Demote,
        
        /// <remarks/>
        SetException,
        
        /// <remarks/>
        ClearException,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class FreezeAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class CheckinAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool autoClassify;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoClassifySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool checkinMinorVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool checkinMinorVersionSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class CheckoutAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reservationId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReservationType reservationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reservationTypeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public enum ReservationType {
        
        /// <remarks/>
        Collaborative,
        
        /// <remarks/>
        Exclusive,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class DeleteAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class UpdateAction : ActionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class CreateAction : ActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool autoUniqueContainmentName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoUniqueContainmentNameSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReservationType reservationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reservationTypeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ChangeRequestType {
        
        /// <remarks/>
        public ObjectReference TargetSpecification;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public ActionType[] Action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public ModifiablePropertyType[] ActionProperties;
        
        /// <remarks/>
        public PropertyFilterType RefreshFilter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int updateSequenceNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateSequenceNumberSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ExecuteChangesRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangeRequest")]
        public ChangeRequestType[] ChangeRequest;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool refresh;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool refreshSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSearchMetadataResponse))]
    public class ObjectSetType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectValue[] Object;
        
        /// <remarks/>
        public CollectionTerminatorType CollectionTerminator;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class GetSearchMetadataResponse : ObjectSetType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string metadataEpochId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ObjectResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectSet", typeof(ObjectSetType))]
        [System.Xml.Serialization.XmlElementAttribute("Object", typeof(ObjectValue))]
        [System.Xml.Serialization.XmlElementAttribute("ErrorStack", typeof(ErrorStackType))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.filenet.com/ns/fnce/2004/06/ws/schema")]
    public class ObjectRequestType {
        
        /// <remarks/>
        public ObjectReference SourceSpecification;
        
        /// <remarks/>
        public PropertyFilterType PropertyFilter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool cacheAllowed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cacheAllowedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxElements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxElementsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string continueFrom;
    }
}
