//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.FSD.Omiga.Web.Services.GetApplicationSummaryDataWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public abstract class OmigaGetApplicationSummaryData : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
        public abstract RESPONSEType getApplicationSummaryData();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class REQUESTType {
        
        /// <remarks/>
        public APPLICATIONRequestType APPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADMINSYSTEMSTATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OPERATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICATIONRequestType {
        
        /// <remarks/>
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        public string APPLICATIONFACTFINDNUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class NEWPROPERTYTypeCOUNTRY {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALUEIDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class NEWPROPERTYTypeVALUATIONTYPE {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALUEIDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class NEWPROPERTYType {
        
        /// <remarks/>
        public NEWPROPERTYTypeVALUATIONTYPE VALUATIONTYPE;
        
        /// <remarks/>
        public string FLATNUMBER;
        
        /// <remarks/>
        public string BUILDINGORHOUSENAME;
        
        /// <remarks/>
        public string BUILDINGORHOUSENUMBER;
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string DISTRICT;
        
        /// <remarks/>
        public string TOWN;
        
        /// <remarks/>
        public string COUNTY;
        
        /// <remarks/>
        public NEWPROPERTYTypeCOUNTRY COUNTRY;
        
        /// <remarks/>
        public string POSTCODE;
        
        /// <remarks/>
        public string COUNTRYCODE;
        
        /// <remarks/>
        public string AREACODE;
        
        /// <remarks/>
        public string TELEPHONENUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICATIONLEGALREPType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DIRECTORYGUID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICATIONPRIORITYVALUEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICATIONSTAGEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short STAGENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STAGENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STAGENAME;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class TYPEOFBUYERType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class TYPEOFAPPLICATIONType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class EMPLOYMENTSTATUSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class OCCUPATIONTYPEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class MARITALSTATUSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class TITLEOTHERType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class TITLEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class CUSTOMERSTATUSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TEXTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class CUSTOMERROLETYPEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short VALUEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICANTType {
        
        /// <remarks/>
        public string CUSTOMERNUMBER;
        
        /// <remarks/>
        public string CUSTOMERVERSIONNUMBER;
        
        /// <remarks/>
        public string CUSTOMERORDER;
        
        /// <remarks/>
        public CUSTOMERROLETYPEType CUSTOMERROLETYPE;
        
        /// <remarks/>
        public CUSTOMERSTATUSType CUSTOMERSTATUS;
        
        /// <remarks/>
        public TITLEType TITLE;
        
        /// <remarks/>
        public TITLEOTHERType TITLEOTHER;
        
        /// <remarks/>
        public string FIRSTFORENAME;
        
        /// <remarks/>
        public string SECONDFORENAME;
        
        /// <remarks/>
        public string OTHERFORENAMES;
        
        /// <remarks/>
        public string SURNAME;
        
        /// <remarks/>
        public string DATEOFBIRTH;
        
        /// <remarks/>
        public MARITALSTATUSType MARITALSTATUS;
        
        /// <remarks/>
        public string MEMBEROFSTAFF;
        
        /// <remarks/>
        public OCCUPATIONTYPEType OCCUPATIONTYPE;
        
        /// <remarks/>
        public EMPLOYMENTSTATUSType EMPLOYMENTSTATUS;
        
        /// <remarks/>
        public string DATESTARTEDORESTABLISHED;
        
        /// <remarks/>
        public string NETMONTHLYINCOME;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class APPLICATIONResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("APPLICANT")]
        public APPLICANTType[] APPLICANT;
        
        /// <remarks/>
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        public string APPLICATIONFACTFINDNUMBER;
        
        /// <remarks/>
        public int AMOUNTREQUESTED;
        
        /// <remarks/>
        public TYPEOFAPPLICATIONType TYPEOFAPPLICATION;
        
        /// <remarks/>
        public TYPEOFBUYERType TYPEOFBUYER;
        
        /// <remarks/>
        public string APPLICATIONDATE;
        
        /// <remarks/>
        public APPLICATIONSTAGEType APPLICATIONSTAGE;
        
        /// <remarks/>
        public APPLICATIONPRIORITYVALUEType APPLICATIONPRIORITYVALUE;
        
        /// <remarks/>
        public string APPLICATIONRECOMMENDEDDATE;
        
        /// <remarks/>
        public string APPLICATIONAPPROVALDATE;
        
        /// <remarks/>
        public APPLICATIONLEGALREPType APPLICATIONLEGALREP;
        
        /// <remarks/>
        public string COMPLETIONDATE;
        
        /// <remarks/>
        public string ADVANCEDATE;
        
        /// <remarks/>
        public short QUOTENUMBER;
        
        /// <remarks/>
        public string MORTGAGEPRODUCTCODE;
        
        /// <remarks/>
        public string OPTOUTINDICATOR;
        
        /// <remarks/>
        public NEWPROPERTYType NEWPROPERTY;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.GetApplicationSummaryData.IDUK.Omiga.marlboroughstirling.com")]
    public class RESPONSEType {
        
        /// <remarks/>
        public APPLICATIONResponseType APPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
