dim obj
set obj  = createobject("MessageQueueListener.MessageQueueListener1.1")
if not obj is nothing then
	strXML = "<?xml version=""1.0""?>"
	strXML = strXML & "<REQUEST ACTION = ""CREATE"">"
	strXML = strXML & "<QUEUELIST>"
	strXML = strXML & "<QUEUE>"
	strXML = strXML & "<NAME>.\Andy</NAME>"
	strXML = strXML & "<TYPE>MSMQ1</TYPE>"
	strXML = strXML & "<THREADSLIST>"
	strXML = strXML & "<THREADS>"
	strXML = strXML & "<NUMBER>4</NUMBER>"
	strXML = strXML & "</THREADS>"
	strXML = strXML & "<THREADS>"
	strXML = strXML & "<NUMBER>6</NUMBER>"
	strXML = strXML & "<DAY>Monday</DAY>"
	strXML = strXML & "<TIME>09:07</TIME>"
	strXML = strXML & "</THREADS>"
	strXML = strXML & "<THREADS>"
	strXML = strXML & "<NUMBER>30</NUMBER>"
	strXML = strXML & "<DAY>Monday</DAY>"
	strXML = strXML & "<TIME>09:07</TIME>"
	strXML = strXML & "</THREADS>"
	strXML = strXML & "<THREADS>"
	strXML = strXML & "<NUMBER>12</NUMBER>"
	strXML = strXML & "<DAY>Friday</DAY>"
	strXML = strXML & "<TIME>17:35</TIME>"
	strXML = strXML & "</THREADS>"
	strXML = strXML & "</THREADSLIST>"
	strXML = strXML & "</QUEUE>"
	strXML = strXML & "</QUEUELIST>"
	strXML = strXML & "</REQUEST>"
	MsgBox obj.Configure(strXML),,"Configure Listener"
	set obj = nothing
else
	msmgbox "Could not create object"
end if
