//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.FSD.Omiga.Web.Services.FindBusinessForCustomerWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public abstract class OmigaFindBusinessForCustomer : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
        public abstract RESPONSEType findBusinessForCustomer();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class REQUESTType {
        
        /// <remarks/>
        public CUSTOMERType CUSTOMER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADMINSYSTEMSTATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("SEARCH")]
        public string OPERATION = "SEARCH";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("SEARCH")]
        public string ACTION = "SEARCH";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class CUSTOMERType {
        
        /// <remarks/>
        public string CUSTOMERNUMBER;
        
        /// <remarks/>
        public string OTHERSYSTEMCUSTOMERNUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class CUSTOMERROLETYPEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class LEVELOFADVICEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class TYPEOFAPPLICATIONType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class EXISTINGBUSINESSType {
        
        /// <remarks/>
        public string BUSINESSTYPE;
        
        /// <remarks/>
        public string BUSINESSTYPEINDICATOR;
        
        /// <remarks/>
        public string PACKAGENUMBER;
        
        /// <remarks/>
        public string APPLICATIONNUMBERORACCOUNTNUMBER;
        
        /// <remarks/>
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        public string ACCOUNTNUMBER;
        
        /// <remarks/>
        public string APPLICATIONFACTFINDNUMBER;
        
        /// <remarks/>
        public string DATECREATED;
        
        /// <remarks/>
        public string AMOUNT;
        
        /// <remarks/>
        public string STATUS;
        
        /// <remarks/>
        public string CORRESPONDENCESALUTATION;
        
        /// <remarks/>
        public TYPEOFAPPLICATIONType TYPEOFAPPLICATION;
        
        /// <remarks/>
        public LEVELOFADVICEType LEVELOFADVICE;
        
        /// <remarks/>
        public string NUMBEROFAPPLICANTS;
        
        /// <remarks/>
        public CUSTOMERROLETYPEType CUSTOMERROLETYPE;
        
        /// <remarks/>
        public string DRAWDOWN;
        
        /// <remarks/>
        public string OVERPAYMENTS;
        
        /// <remarks/>
        public string LOANCLASSTYPE;
        
        /// <remarks/>
        public string TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class EXISTINGBUSINESSLISTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXISTINGBUSINESS")]
        public EXISTINGBUSINESSType[] EXISTINGBUSINESS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindBusinessForCustomer.IDUK.Omiga.marlboroughstirling.com")]
    public class RESPONSEType {
        
        /// <remarks/>
        public EXISTINGBUSINESSLISTType EXISTINGBUSINESSLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.IDUK.Omiga.marlboroughstirling.com")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
