VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IBuildingsAndContentsSubQuoteBO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function CreateSubQuoteDetails(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function CreateValuablesOverLimit(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function UpdateValuablesOverLimit(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function CreateFirstSubQuote(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function CreateNewSubQuote(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function UpdateSubQuoteDetails(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function DeleteValuablesOverLimit(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function GetSubQuoteDetails(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function GetBCNotes(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function GetPaymentFrequency(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function BuildBCCalcInterface(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function Validate(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function FindList(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function FindValuablesOverLimitList(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function DeleteAll(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function SaveBCNotes(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function SaveSubQuote(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function ValidateSubQuote(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function
Public Function DeleteAllValuables(ByVal vXMLRequest As IXMLDOMElement) As IXMLDOMNode
End Function

Public Sub GetInsuranceAdminFee(ByVal vXMLRequest As IXMLDOMElement, ByVal vXMLResponse As IXMLDOMElement)

End Sub

