Attribute VB_Name = "Globals"
Option Explicit

'================================================================================================
' Epsom change history
' PB    16/05/2006  EP529   MAR1731 Fulfilemnt - Offer Document - oncorrect validity period shown
' INR   23/11/2006  EP2_139 For New Introducer structure.
' PB    11/12/2006  EP2_139 New Offer Doc changes for Epsom Phase 2
' INR   12/12/2006  EP2_422   Section13 changes
'================================================================================================

'*-INPUT DATA NODE STRUCTURE
'       [1] can only be 1 node
'       [X] can be many nodes

'[1]    APPLICATION
'[X]        APPLICATIONCONDITIONS
'[1]        INTERMEDIARY
'[1]            ADDRESS
'[1]            CONTACTDETAILS
'[1]            INTERMEDIARYORGANISATION
'[1]            INTERMEDIARYINDIVIDUAL
'[1]        APPLICATIONFACTFIND - DB allows X - so must be restricted at extraction
'[1]            QUOTATION - DB allows X - so must be restricted at extraction
'[1]                MORTGAGESUBQUOTE - DB allows X - so must be restricted at extraction
'[X]                    MORTGAGEONEOFFCOST
'[X]                    LOANCOMPONENT
'[1]                        LOANCOMPONENTBALANCESCHEDULE
'[X]                        LOANCOMPONENTPAYMENTSCHEDULE
'[X]                        LOANCOMPONENTREDEMPTIONFEE
'[1]                        MORTGAGELOAN
'[1]                        MORTGAGEPRODUCT
'[X]                            MORTGAGEPRODUCTLANGUAGE
'[1]                            MORTGAGEPRODUCTPARAMETERS
'[1]                            MORTGAGELENDER
'[X]                                MORTGAGELENDERDIRECTORY
'[1]                                    NAMEANDADDRESSDIRECTORY
'[1]                                        CONTACTDETAILS
'[1]                                        ADDRESS
'[1]                                MORTGAGELENDERPARAMETERS
'[X]                            INTERESTRATETYPE
'[1]                                BASERATESETDATA
'[X]                                    BASERATE
'[X]                                    BASERATEBAND
'[X]            VALUERINSTRUCTION
'[1]                VALNREPVALUATION
'[X]            CUSTOMERROLE
'[1]                CUSTOMERVERSION
'[1]                    CUSTOMERADDRESS
'[1]                        ADDRESS
'[X]            VALNREPPROPERTYDETAILS
'[1]            NEWPROPERTY
'[1]                   NEWPROPERTYADDRESS
'[1]                        ADDRESS
'[X]            CUSTOMERADDED
'[X]            CUSTOMERREMOVED
'[X]            MEMOPAD
'[X]        APPLICATIONFEETYPE
'[1]    GLOBALDATAITEM

Public Const gcstrAPPLICATION_PATH As String = "//APPLICATION"
Public Const gcstrAPPLICATIONCONDITIONS_PATH As String = "//APPLICATION/APPLICATIONCONDITIONS"
Public Const gcstrAPPLICATIONFACTFIND_PATH As String = "//APPLICATION/APPLICATIONFACTFIND"
Public Const gcstrQUOTATION_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION"
Public Const gcstrMORTGAGESUBQUOTE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE"
Public Const gcstrMORTGAGEONEOFFCOSTS_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/MORTGAGEONEOFFCOST"
Public Const gcstrLOANCOMPONENT_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT"
Public Const gcstrMORTGAGELOAN_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGELOAN"
Public Const gcstrMORTGAGEPRODUCT_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGEPRODUCT"
Public Const gcstrMORTGAGELENDER_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGEPRODUCT/MORTGAGELENDER"
Public Const gcstrMORTGAGELENDERPARAMS_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGEPRODUCT/MORTGAGELENDER/MORTGAGELENDERPARAMETERS"
Public Const gcstrINTERESTRATETYPE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGEPRODUCT/INTERESTRATETYPE"
Public Const gcstrCUSTOMERROLE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/CUSTOMERROLE"
Public Const gcstrCUSTOMERVERSION_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/CUSTOMERROLE/CUSTOMERVERSION"
Public Const gcstrNANDADIRECTORY_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/LOANCOMPONENT/MORTGAGEPRODUCT/MORTGAGELENDER/MORTGAGELENDERDIRECTORY/NAMEANDADDRESSDIRECTORY"
Public Const gcstrVALUATIONINSTRUCTIONS_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/VALUERINSTRUCTION"
Public Const gcstrAPPLICATIONINTERMEDIARY_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTERMEDIARY"
Public Const gcstrOTHERINSURANCECOMPANY_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/OTHERINSURANCECOMPANY"
Public Const gcstrLIFESUBQUOTE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/LIFESUBQUOTE"
Public Const gcstrPAYMENTPROTECTIONSUBQUOTE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/PAYMENTPROTECTIONSUBQUOTE"
Public Const gcstrBUILDINGSANDCONTENTSSUBQUOTE_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/BUILDINGSANDCONTENTSSUBQUOTE"
'Public Const gcstrINTERMEDIARYADDRESS_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTERMEDIARY/INTERMEDIARY/ADDRESS"    'SAB 24/04/2006 : EPSOM - EP417
Public Const gcstrACCOUNTRELATIONSHIP_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/CUSTOMERROLE/CUSTOMERVERSION/ACCOUNTRELATIONSHIP"
'Public Const gcstrINTERMEDIARYORGANISATION_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTERMEDIARY/INTERMEDIARY/INTERMEDIARYORGANISATION"   'SAB 24/04/2006 : EPSOM - EP417
'SR 11/09/2004 : CORE82 - Modfied path gcstrINTERMEDIARYINDIVIDUAL_PATH
'Public Const gcstrINTERMEDIARYINDIVIDUAL_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTERMEDIARY/INTERMEDIARY/INTERMEDIARYINDIVIDUAL"   'SAB 24/04/2006 : EPSOM - EP417
'Public Const gcstrINTERMEDIARYCONTACTDETAILS_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTERMEDIARY/INTERMEDIARY/INTERMEDIARYINDIVIDUAL/INTERMEDIARYCONTACT/CONTACTTELEPHONEDETAILS"   'SAB 24/04/2006 : EPSOM - EP417
Public Const gcstrCUSTOMERADDED_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/CUSTOMERADDED"
Public Const gcstrREMOVEDTOECUSTOMER_PATH As String = "//APPLICATION/REMOVEDTOECUSTOMER"
'PB  16/05/2006 : EP529 / MAR1731
Public Const gcstrPROPERTYLOCATION_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/NEWPROPERTY"
'INR 02/11/2004 : BBG1739
Public Const gcstrLEGALREP_PATH As String = "//APPLICATION/LEGALREP"

'SAB 24/04/2006 : EPSOM - EP417 : START
Public Const gcstrINTERMEDIARY_PATH As String = "//APPLICATION/INTERMEDIARY"
Public Const gcstrINTERMEDIARYADDRESS_PATH As String = "//APPLICATION/INTERMEDIARY/ADDRESS"
Public Const gcstrINTERMEDIARYORGANISATION_PATH As String = "//APPLICATION/INTERMEDIARY/INTERMEDIARYORGANISATION"
Public Const gcstrINTERMEDIARYINDIVIDUAL_PATH As String = "//APPLICATION/INTERMEDIARY/INTERMEDIARYINDIVIDUAL"
Public Const gcstrINTERMEDIARYCONTACTDETAILS_PATH As String = "//APPLICATION/INTERMEDIARY/INTERMEDIARYINDIVIDUAL/INTERMEDIARYCONTACT/CONTACTTELEPHONEDETAILS"
Public Const gcstrMEMOPAD_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/MEMOPAD"
Public Const gcstrPANELLEGALREP_PATH As String = "//APPLICATION/LEGALREP/NAMEANDADDRESSDIRECTORY/PANEL"
'SAB 24/04/2006 : EPSOM - EP417 : END

'PM 19/05/2006 : EPSOM - EP584 : START
Public Const gcstrBROKER_PATH As String = "//APPLICATION/BROKER"
Public Const gcstrBROKERINTERMEDIARY_PATH As String = "//APPLICATION/BROKER/INTERMEDIARY"
'PM 19/05/2006 : EPSOM - EP584 : END
'EP2_139
Public Const gcstrAPPINTRODUCER_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER"
Public Const gcstrINTRODUCER_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER/INTRODUCER"
Public Const gcstrORGANISATIONUSER_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER/INTRODUCER/ORGANISATIONUSER"
Public Const gcstrARFIRM_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER[ARFIRM]"
Public Const gcstrPRINCIPALFIRM_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER[PRINCIPALFIRM]"
'EP2_422   Section13 changes
Public Const gcstrMORTGAGECLUBNETWORKASSOC_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/APPLICATIONINTRODUCER[MORTGAGECLUBNETWORKASSOCIATION]"
Public Const gcstrAPPPROCFEES_PATH As String = "//APPLICATION/APPLICATIONFACTFIND/QUOTATION/MORTGAGESUBQUOTE/MORTGAGEINTRODUCERFEE"

