//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace Vertex.Fsd.Omiga.Web.Services.FindDirectoryListWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://FindDirectoryList.Omiga.vertex.co.uk")]
    public abstract class OmigaFindDirectoryList : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.FindDirectoryList.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.FindDirectoryList.Omiga.vertex.co.uk")]
        public abstract RESPONSEType findDirectoryList();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindDirectoryList.Omiga.vertex.co.uk")]
    public class REQUESTType {
        
        /// <remarks/>
        public NAMEANDADDRESSDIRECTORYRequestType NAMEANDADDRESSDIRECTORY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.FindDirectoryList.Omiga.vertex.co.uk")]
    public class NAMEANDADDRESSDIRECTORYRequestType {
        
        /// <remarks/>
        public string PANELID;
        
        /// <remarks/>
        public string COMPANYNAME;
        
        /// <remarks/>
        public string TOWN;
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string POSTCODE;
        
        /// <remarks/>
        public string BUILDINGORHOUSENAME;
        
        /// <remarks/>
        public int BUILDINGORHOUSENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BUILDINGORHOUSENUMBERSpecified;
        
        /// <remarks/>
        public string FLATNUMBER;
        
        /// <remarks/>
        public string FILTER;
        
        /// <remarks/>
        public string NAMEANDADDRESSTYPE;
        
        /// <remarks/>
        public string SORTCODE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public string SQLCOMMAND;
        
        /// <remarks/>
        public string COMPONENT_ID;
        
        /// <remarks/>
        public string COMPONENT_RESPONSE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class CONTACTTELEPHONEDETAILSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTDETAILSGUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TELEPHONESEQNUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TELEPHONESEQNUMSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int USAGE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USAGESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EXTENSIONNUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class CONTACTDETAILSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTACTTELEPHONEDETAILS")]
        public CONTACTTELEPHONEDETAILSType[] CONTACTTELEPHONEDETAILS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTDETAILSGUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTFORENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTSURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTTITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CONTACTTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CONTACTTYPESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EMAILADDRESS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONEEXTENSIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONENUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindDirectoryList.Omiga.vertex.co.uk")]
    public class NAMEANDADDRESSDIRECTORYResponseType {
        
        /// <remarks/>
        public string DIRECTORYGUID;
        
        /// <remarks/>
        public string NAMEANDADDRESSTYPE;
        
        /// <remarks/>
        public string COMPANYNAME;
        
        /// <remarks/>
        public string HEADOFFICEINDICATOR;
        
        /// <remarks/>
        public string NAMEANDADDRESSBANKSORTCODE;
        
        /// <remarks/>
        public string BUILDINGORHOUSENAME;
        
        /// <remarks/>
        public string BUILDINGORHOUSENUMBER;
        
        /// <remarks/>
        public string FLATNUMBER;
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string DISTRICT;
        
        /// <remarks/>
        public string TOWN;
        
        /// <remarks/>
        public string COUNTY;
        
        /// <remarks/>
        public string COUNTRY;
        
        /// <remarks/>
        public string POSTCODE;
        
        /// <remarks/>
        public string PANELID;
        
        /// <remarks/>
        public string COUNTRYCODE;
        
        /// <remarks/>
        public string AREACODE;
        
        /// <remarks/>
        public string TELENUMBER;
        
        /// <remarks/>
        public string EXTENSIONNUMBER;
        
        /// <remarks/>
        public short STATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STATUSSpecified;
        
        /// <remarks/>
        public CONTACTDETAILSType CONTACTDETAILS;
        
        /// <remarks/>
        public string DXID;
        
        /// <remarks/>
        public string DXLOCATION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindDirectoryList.Omiga.vertex.co.uk")]
    public class NAMEANDADDRESSDIRECTORYLISTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAMEANDADDRESSDIRECTORY")]
        public NAMEANDADDRESSDIRECTORYResponseType[] NAMEANDADDRESSDIRECTORY;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.FindDirectoryList.Omiga.vertex.co.uk")]
    public class RESPONSEType {
        
        /// <remarks/>
        public NAMEANDADDRESSDIRECTORYLISTType NAMEANDADDRESSDIRECTORYLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
