//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.Fsd.Omiga.Web.Services.CreateKFIWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://CreateKFI.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APPLICATIONINTRODUCER_base))]
    public abstract class OmigaCreateKFI : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.CreateKFI.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
        public abstract RESPONSEType createKFI([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")] REQUESTType REQUEST);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.CalculateKFIFees.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.CalculateKFIFees.Omiga.vertex.co.uk")]
        public abstract CALCKFIFEESRESPONSEType calculateKFIFees([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")] CALCKFIFEESREQUESTType REQUEST);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class REQUESTType {
        
        /// <remarks/>
        public APPLICATIONRequestType APPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CUSTOMER", IsNullable=false)]
        public CUSTOMERRequestType[] CUSTOMERLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONRequestType {
        
        /// <remarks/>
        public APPLICATIONFACTFINDRequestType APPLICATIONFACTFIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TYPEOFBUYER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TYPEOFVALUATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short DISPOSABLEKFI;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PROCFEETOCUST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PROCFEETOCUSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Decimal PROCFEETOCUSTAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PROCFEETOCUSTAMOUNTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONFACTFINDRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("APPLICATIONINTRODUCER", IsNullable=false)]
        public APPLICATIONINTRODUCERRequestType[] APPLICATIONINTRODUCERLIST;
        
        /// <remarks/>
        public QUOTATIONRequestType QUOTATION;
        
        /// <remarks/>
        public NEWPROPERTYRequestType NEWPROPERTY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LOCATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PURCHASEPRICE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PURCHASEPRICESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short INCREMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCREMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short REGULATIONINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LEVELOFADVICE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TYPEOFAPPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short NATUREOFLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PRODUCTSCHEME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRODUCTSCHEMESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SPECIALSCHEME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPECIALSCHEMESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int APPLICATIONINCOMESTATUS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONINTRODUCERRequestType : APPLICATIONINTRODUCER_base {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OmigaBase.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APPLICATIONINTRODUCERRequestType))]
    public class APPLICATIONINTRODUCER_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int APPLICATIONINTRODUCERSEQNO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APPLICATIONINTRODUCERSEQNOSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int APPLICATIONFACTFINDNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APPLICATIONFACTFINDNUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CLUBNETWORKASSOCID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTRODUCERID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class FEEResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IDENTIFIER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short CANBEADDEDTOLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short CANBEREFUNDED;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESRESPONSEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FEE", IsNullable=false)]
        public FEEResponseType[] FEELIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public SQLCOMMANDType SQLCOMMAND;
        
        /// <remarks/>
        public string COMPONENT_ID;
        
        /// <remarks/>
        public string COMPONENT_RESPONSE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLCOMMANDType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SQLPARAM")]
        public SQLPARAMType[] SQLPARAM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMMANDTEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLPARAMType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DIRECTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESCUSTOMERRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIRSTNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OTHERNAMES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GENDER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATEOFBIRTH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESLOANCOMPONENTRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MORTGAGEPRODUCTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STARTDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TERMINYEARS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TERMINMONTHS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TERMINMONTHSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TOTALLOANCOMPONENTAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string REPAYMENTMETHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETCAPANDINTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETCAPANDINTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETINTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETINTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CAPITALANDINTERESTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPITALANDINTERESTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTERESTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LIFETIMEINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LIFETIMEINDICATORSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PURPOSEOFLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short REPAYMENTVEHICLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTVEHICLESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single REPAYMENTVEHICLEMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTVEHICLEMONTHLYCOSTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESMORTGAGESUBQUOTERequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LOANCOMPONENT", IsNullable=false)]
        public CALCKFIFEESLOANCOMPONENTRequestType[] LOANCOMPONENTLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNTREQUESTED;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESQUOTATIONRequestType {
        
        /// <remarks/>
        public CALCKFIFEESMORTGAGESUBQUOTERequestType MORTGAGESUBQUOTE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESAPPLICATIONFACTFINDRequestType {
        
        /// <remarks/>
        public CALCKFIFEESQUOTATIONRequestType QUOTATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LOCATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PURCHASEPRICE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PURCHASEPRICESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short INCREMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCREMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short REGULATIONINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LEVELOFADVICE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TYPEOFAPPLICATION;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESAPPLICATIONRequestType {
        
        /// <remarks/>
        public CALCKFIFEESAPPLICATIONFACTFINDRequestType APPLICATIONFACTFIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TYPEOFVALUATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short DISPOSABLEKFI;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CalculateKFIFees.Omiga.vertex.co.uk")]
    public class CALCKFIFEESREQUESTType {
        
        /// <remarks/>
        public CALCKFIFEESAPPLICATIONRequestType APPLICATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CUSTOMER", IsNullable=false)]
        public CALCKFIFEESCUSTOMERRequestType[] CUSTOMERLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class DOCUMENTCONTENTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public System.Byte[] CONTENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTENTTYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class DOCUMENTLOCATIONType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DOCUMENTID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class CUSTOMERVERSIONType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIRSTFORENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OTHERFORENAMES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SECONDFORENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TITLESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TITLEOTHER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class CUSTOMERRespnseType {
        
        /// <remarks/>
        public CUSTOMERVERSIONType CUSTOMERVERSION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CUSTOMERNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OTHERSYSTEMCUSTOMERNUMBER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class ONEOFFCOSTType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REFUNDAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REFUNDAMOUNTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MORTGAGEONEOFFCOSTTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ONEOFFCOSTSEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ONEOFFCOSTSEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ADHOCIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADHOCINDSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONFEETYPEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FEETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEETYPESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FEETYPESEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEETYPESEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REBATEORADDITION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REBATEORADDITIONSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ADHOCIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADHOCINDSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class LOANCOMPONENTBALANCESCHEDULEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTSEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTSEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTBALANCESCHEDULEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTBALANCESCHEDULEIDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SCHEDULETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SCHEDULETYPESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STARTDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single BALANCE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BALANCESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single INTONLYBALANCE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTONLYBALANCESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single CAPINTBALANCE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPINTBALANCESpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class LOANCOMPONENTREDEMPTIONFEEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTSEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTSEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int APPLICATIONFACTFINDNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APPLICATIONFACTFINDNUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MORTGAGESUBQUOTENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MORTGAGESUBQUOTENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REDEMPTIONFEESTEPNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REDEMPTIONFEESTEPNUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REDEMPTIONFEEPERIOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REDEMPTIONFEEPERIODSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string REDEMPTIONFEEPERIODENDDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single REDEMPTIONFEEAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REDEMPTIONFEEAMOUNTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class LOANCOMPONENTPAYMENTSCHEDULEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTSEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTSEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTPAYMENTSCHEDULEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTPAYMENTSCHEDULEIDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTERESTRATETYPESEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTRATETYPESEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STARTDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single MONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single INTONLYMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTONLYMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single CAPINTMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPINTMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single MINMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MINMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single MAXMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MAXMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single INCREASEDMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCREASEDMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single INCREASEDMONTHLYCOSTDIFFERENCE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCREASEDMONTHLYCOSTDIFFERENCESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PAYMENTTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single INTERESTRATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTRATESpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class LOANCOMPONENTResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOANCOMPONENTPAYMENTSCHEDULE")]
        public LOANCOMPONENTPAYMENTSCHEDULEType[] LOANCOMPONENTPAYMENTSCHEDULE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOANCOMPONENTREDEMPTIONFEE")]
        public LOANCOMPONENTREDEMPTIONFEEType[] LOANCOMPONENTREDEMPTIONFEE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOANCOMPONENTBALANCESCHEDULE")]
        public LOANCOMPONENTBALANCESCHEDULEType[] LOANCOMPONENTBALANCESCHEDULE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LOANCOMPONENTSEQUENCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOANCOMPONENTSEQUENCENUMBERSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TOTALLOANCOMPONENTAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTALLOANCOMPONENTAMOUNTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single GROSSMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROSSMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single NETMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single MONTHLYCOSTLESSDRAWDOWN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MONTHLYCOSTLESSDRAWDOWNSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTERESTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CAPITALANDINTERESTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPITALANDINTERESTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETCAPANDINTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETCAPANDINTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETINTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETINTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PORTEDLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PORTEDLOANSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PURPOSEOFLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PURPOSEOFLOANSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REPAYMENTMETHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTMETHODSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TERMINMONTHS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TERMINMONTHSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TERMINYEARS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TERMINYEARSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single APR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APRSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single FINALPAYMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FINALPAYMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single FINALRATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FINALRATESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single FINALRATEMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FINALRATEMONTHLYCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single RESOLVEDRATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RESOLVEDRATESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single AMOUNTPERUNITBORROWED;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTPERUNITBORROWEDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single ACCRUEDINTEREST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCRUEDINTERESTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALAMOUNTPAYABLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTALAMOUNTPAYABLESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MORTGAGEPRODUCTCODE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class MORTGAGESUBQUOTEResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LOANCOMPONENT", IsNullable=false)]
        public LOANCOMPONENTResponseType[] LOANCOMPONENTLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALGROSSMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single MONTHLYCOSTLESSDRAWDOWN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MONTHLYCOSTLESSDRAWDOWNSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TOTALACCRUEDINTEREST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single AMOUNTPERUNITBORROWED;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single APR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALAMOUNTPAYABLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALMORTGAGEPAYMENTS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class QUOTATIONResponseType {
        
        /// <remarks/>
        public MORTGAGESUBQUOTEResponseType MORTGAGESUBQUOTE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALQUOTATIONCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTALQUOTATIONCOSTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short KFIPRINTEDINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KFIPRINTEDINDICATORSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONFACTFINDResponseType {
        
        /// <remarks/>
        public QUOTATIONResponseType QUOTATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single TOTALMONTHLYREPAYMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTALMONTHLYREPAYMENTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class APPLICATIONResponseType {
        
        /// <remarks/>
        public APPLICATIONFACTFINDResponseType APPLICATIONFACTFIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("APPLICATIONFEETYPE")]
        public APPLICATIONFEETYPEType[] APPLICATIONFEETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ONEOFFCOST")]
        public ONEOFFCOSTType[] ONEOFFCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short UNDERWRITERSDECISION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UNDERWRITERSDECISIONSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.CreateKFI.Omiga.vertex.co.uk")]
    public class RESPONSEType {
        
        /// <remarks/>
        public APPLICATIONResponseType APPLICATION;
        
        /// <remarks/>
        public CUSTOMERRespnseType CUSTOMER;
        
        /// <remarks/>
        public DOCUMENTLOCATIONType DOCUMENTLOCATION;
        
        /// <remarks/>
        public DOCUMENTCONTENTType DOCUMENTCONTENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class CUSTOMERRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIRSTNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OTHERNAMES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GENDER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATEOFBIRTH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class NEWPROPERTYRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PROPERTYLOCATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int VALUATIONTYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class FEERequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IDENTIFIER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ADDEDTOLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int REFUNDAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REFUNDAMOUNTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ADHOCIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADHOCINDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PAIDATEND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PAIDATENDSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class LOANCOMPONENTRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MORTGAGEPRODUCTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STARTDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TERMINYEARS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short TERMINMONTHS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TERMINMONTHSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TOTALLOANCOMPONENTAMOUNT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string REPAYMENTMETHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETCAPANDINTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETCAPANDINTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NETINTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETINTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CAPITALANDINTERESTELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAPITALANDINTERESTELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTERESTONLYELEMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTERESTONLYELEMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short LIFETIMEINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LIFETIMEINDICATORSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short PURPOSEOFLOAN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short REPAYMENTVEHICLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTVEHICLESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single REPAYMENTVEHICLEMONTHLYCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REPAYMENTVEHICLEMONTHLYCOSTSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class MORTGAGESUBQUOTERequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LOANCOMPONENT", IsNullable=false)]
        public LOANCOMPONENTRequestType[] LOANCOMPONENTLIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FEE", IsNullable=false)]
        public FEERequestType[] FEELIST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AMOUNTREQUESTED;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Double DRAWDOWN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DRAWDOWNSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.CreateKFI.Omiga.vertex.co.uk")]
    public class QUOTATIONRequestType {
        
        /// <remarks/>
        public MORTGAGESUBQUOTERequestType MORTGAGESUBQUOTE;
    }
}
