' Initialise SPM for Omiga 4

dim GlobalParameterBO
set GlobalParameterBO = createobject("omBase.GlobalParameterBO")

GlobalParameterBO.GetCurrentParameter("AddToDirectoryRole")
GlobalParameterBO.GetCurrentParameter("BCInsPremTaxRate")
GlobalParameterBO.GetCurrentParameter("BCValuablesOverLimit")
GlobalParameterBO.GetCurrentParameter("BCValuablesTotalLimit")
GlobalParameterBO.GetCurrentParameter("BuildingsCoverAmount")
GlobalParameterBO.GetCurrentParameter("ComponentForAddedCosts")
GlobalParameterBO.GetCurrentParameter("ContentsCoverAmount")
GlobalParameterBO.GetCurrentParameter("CreditCheckAvailable")
GlobalParameterBO.GetCurrentParameter("DefaultLTV")
GlobalParameterBO.GetCurrentParameter("FindLegacyCustomer")
GlobalParameterBO.GetCurrentParameter("FindLegacyCustomerByName")
GlobalParameterBO.GetCurrentParameter("IncludeGuarantors")
GlobalParameterBO.GetCurrentParameter("LifeCoverIPTRate")
GlobalParameterBO.GetCurrentParameter("Locking")
GlobalParameterBO.GetCurrentParameter("MIGInsPremTaxRate")
GlobalParameterBO.GetCurrentParameter("MIRASInterestRate")
GlobalParameterBO.GetCurrentParameter("MaxChangePasswordAttempts")
GlobalParameterBO.GetCurrentParameter("MaxLogonAttempts")
GlobalParameterBO.GetCurrentParameter("MaximumAge")
GlobalParameterBO.GetCurrentParameter("MaximumApplicants")
GlobalParameterBO.GetCurrentParameter("MaximumCustomers")
GlobalParameterBO.GetCurrentParameter("MaximumGuarantors")
GlobalParameterBO.GetCurrentParameter("MaximumMIRASRelief")
GlobalParameterBO.GetCurrentParameter("MaximumPasswords")
GlobalParameterBO.GetCurrentParameter("MaximumQQComponents")
GlobalParameterBO.GetCurrentParameter("MaximumTerm")
GlobalParameterBO.GetCurrentParameter("MinimumAge")
GlobalParameterBO.GetCurrentParameter("MinimumTerm")
GlobalParameterBO.GetCurrentParameter("MortProdSelectionVersion")
GlobalParameterBO.GetCurrentParameter("MortgageProductMaxRecords")
GlobalParameterBO.GetCurrentParameter("Omiga4To3DownloadAvailable")
GlobalParameterBO.GetCurrentParameter("OtherSystemReadOnlyCustomer")
GlobalParameterBO.GetCurrentParameter("PAFOnline")
GlobalParameterBO.GetCurrentParameter("PAFTimeOut")
GlobalParameterBO.GetCurrentParameter("PPInsPremTaxRate")
GlobalParameterBO.GetCurrentParameter("PPMaximumCover")
GlobalParameterBO.GetCurrentParameter("PPRoundingFactor")
GlobalParameterBO.GetCurrentParameter("PasswordAlphaNumeric")
GlobalParameterBO.GetCurrentParameter("PasswordCharacterDuplication")
GlobalParameterBO.GetCurrentParameter("PasswordLowerAlpha")
GlobalParameterBO.GetCurrentParameter("PasswordMaximumLength")
GlobalParameterBO.GetCurrentParameter("PasswordMinimumLength")
GlobalParameterBO.GetCurrentParameter("PasswordNoUserId")
GlobalParameterBO.GetCurrentParameter("PasswordNumeric")
GlobalParameterBO.GetCurrentParameter("PasswordSpecialCharacters")
GlobalParameterBO.GetCurrentParameter("PasswordUpperAlpha")
GlobalParameterBO.GetCurrentParameter("PasswordValidDays")
GlobalParameterBO.GetCurrentParameter("PolarisApplicationIdentifier")
GlobalParameterBO.GetCurrentParameter("PolarisApplicationVersion")
GlobalParameterBO.GetCurrentParameter("PolarisSchemeIdentifier")
GlobalParameterBO.GetCurrentParameter("PolarisSchemeVersion")
GlobalParameterBO.GetCurrentParameter("PolarisTransactionType")
GlobalParameterBO.GetCurrentParameter("QQLocation")
GlobalParameterBO.GetCurrentParameter("QQValuationType")
GlobalParameterBO.GetCurrentParameter("RiskAssessmentAvailable")
GlobalParameterBO.GetCurrentParameter("SearchByDistributionChannel")
GlobalParameterBO.GetCurrentParameter("SecurityLevelSupervisor")

msgbox("Initialise Omiga4 complete")
