/*****************************************************************************/
/* File Name:	Default User SQL Server.sql                                  */
/* Description: A script to create the minimum data required to log into     */
/*		Core Supervisor with a blank Omiga4 database.                */
/*                                                                           */
/* Change History                                                            */
/* Prog	Date		Description                                          */
/* STB	24-Jan-02	Created Script                                       */
/* STB  31-Jan-02	Amended the SupervisorUserItem inserts to match the  */
/*                      spec'ed database schema.                             */
/* STB  01-Feb-02	Table name altered to match DB.                      */
/*****************************************************************************/
BEGIN TRANSACTION

PRINT 'Running data setup script. Inserting minimum required data.'

/* COUNTY */
IF NOT EXISTS(SELECT 1 FROM COUNTRY WHERE COUNTRYNUMBER = 1) BEGIN
	PRINT 'Adding Country...'

	INSERT INTO COUNTRY (COUNTRYNUMBER, COUNTRYNAME)
	VALUES	(1, 'England')
END

/* DISTRIBUTIONCHANNEL */
IF NOT EXISTS(SELECT 1 FROM DISTRIBUTIONCHANNEL WHERE CHANNELID = '1') BEGIN
	PRINT 'Adding Distribution Channel...'

	INSERT INTO DISTRIBUTIONCHANNEL (CHANNELID, CHANNELNAME, COUNTRYNUMBER)
	VALUES	('1', 'Default', 1)
END

/* DEPARTMENT */
IF NOT EXISTS(SELECT 1 FROM DEPARTMENT WHERE DEPARTMENTID = '1') BEGIN
	PRINT 'Adding Department...'

	INSERT INTO DEPARTMENT (DEPARTMENTID, DEPARTMENTNAME)
	VALUES	('1', 'Default')
END

/* REGION */
IF NOT EXISTS(SELECT 1 FROM REGION WHERE REGIONID = 1) BEGIN
	PRINT 'Adding Region...'

	INSERT INTO REGION (REGIONID, REGIONNAME, REGIONTYPE)
	VALUES (1, 'Default', 10)
END

/* UNIT */
IF NOT EXISTS(SELECT 1 FROM UNIT WHERE UNITID = 'Default') BEGIN
	PRINT 'Adding Unit...'	

	INSERT INTO UNIT (UNITID, UNITNAME)
	VALUES ('Default', 'Default')
END

/* COMPETENCY */
IF NOT EXISTS(SELECT 1 FROM COMPETENCY WHERE COMPETENCYTYPE = '20') BEGIN
	PRINT 'Adding Competency...'

	INSERT INTO COMPETENCY (COMPETENCYTYPE, COMPETENCYACTIVEFROM)
	VALUES ('20', CONVERT(DATETIME, '2002-01-01 00:00:00', 102))
END

/* WORKINGHOURTYPE */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1) BEGIN
	PRINT 'Adding Working Hours Type...'

	INSERT INTO WORKINGHOURTYPE (WORKINGHOURTYPE, WORKINGHOURTYPEDESCRIPTION)
	VALUES (1, '0:00 - 23:59 Mon - Su')
END

/* WORKINGHOURS Sunday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 1) BEGIN
	PRINT 'Adding Sunday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 1, 'Sunday', 0, 1, 23, 59)
END

/* WORKINGHOURS Monday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 2) BEGIN
	PRINT 'Adding Monday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 2, 'Monday', 0, 1, 23, 59)
END

/* WORKINGHOURS Tuesday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 3) BEGIN
	PRINT 'Adding Tuesday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 3, 'Tuesday', 0, 1, 23, 59)
END

/* WORKINGHOURS Wednesday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 4) BEGIN
	PRINT 'Adding Wednesday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 4, 'Wednesday', 0, 1, 23, 59)
END

/* WORKINGHOURS Thursday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 5) BEGIN
	PRINT 'Adding Thursday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 5, 'Thursday', 0, 1, 23, 59)
END

/* WORKINGHOURS Friday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 6) BEGIN
	PRINT 'Adding Friday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 6, 'Friday', 0, 1, 23, 59)
END

/* WORKINGHOURS Saturday */
IF NOT EXISTS(SELECT 1 FROM WORKINGHOURS WHERE WORKINGHOURTYPE = 1 AND DAYOFTHEWEEK = 7) BEGIN
	PRINT 'Adding Saturday Hours...'

	INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
	VALUES (1, 7, 'Saturday', 0, 1, 23, 59)
END

/* OMIGAUSER */
IF NOT EXISTS(SELECT 1 FROM OMIGAUSER WHERE USERID = 'Default') BEGIN
	PRINT 'Adding OmigaUser...'

	INSERT INTO OMIGAUSER (USERID, OMIGAUSERACTIVEFROM, OMIGAUSERACTIVETO, WORKINGHOURTYPE, ACCESSTYPE)
	VALUES ('Default', CONVERT(DATETIME, '2002-01-01 00:00:00', 102), CONVERT(DATETIME, '2010-01-01 00:00:00', 102), 1, 60)
END

/* ORGANISATIONUSER */
IF NOT EXISTS(SELECT 1 FROM ORGANISATIONUSER WHERE USERID = 'Default') BEGIN
	PRINT 'Adding OrganisationUser...'

	INSERT INTO ORGANISATIONUSER (USERID, DATEOFBIRTH, USERFORENAME, USERINITIALS, USERSURNAME, USERTITLE)
	VALUES ('Default', '01/01/2002', 'default', 'S', 'user', 99)
END

/* PASSWORD (omiga4) */
IF NOT EXISTS(SELECT 1 FROM PASSWORD WHERE USERID = 'Default' AND PASSWORDVALUE = '~Xy~H~?rS') BEGIN
	PRINT 'Adding Password...'	

	INSERT INTO PASSWORD (USERID, PASSWORDVALUE, PASSWORDCREATIONDATE)
	VALUES ('Default', '~Xy~H~?rS', CONVERT(DATETIME, '2002-01-01 00:00:00', 102))
END

/* USERCOMPETENCY */
IF NOT EXISTS(SELECT 1 FROM USERCOMPETENCY WHERE USERID = 'Default' AND COMPETENCYTYPE = '20' AND USERCOMPETENCYACTIVEFROM = CONVERT(DATETIME, '2002-01-01 00:00:00', 102)) BEGIN
	PRINT 'Adding UserCompetency...'

	INSERT INTO USERCOMPETENCY (USERID, COMPETENCYTYPE, USERCOMPETENCYACTIVEFROM, COMPETENCYTYPETEXT)
	VALUES ('Default', '20', CONVERT(DATETIME, '2002-01-01 00:00:00', 102), '500,000 - 100 - 500,000')
END

/* USERROLE */
IF NOT EXISTS(SELECT 1 FROM USERROLE WHERE UNITID = 'Default' AND USERID = 'Default') BEGIN
	PRINT 'Adding UserRole...'
	
	INSERT INTO USERROLE (UNITID, USERID, USERROLEACTIVEFROM, ROLE, USERROLETEXT)
	VALUES ('Default', 'Default', CONVERT(DATETIME, '2002-01-01 00:00:00', 102), 99, 'System Administrator')
END

/* COMBOGROUP: UserRole */
IF NOT EXISTS(SELECT 1 FROM COMBOGROUP WHERE GROUPNAME = 'UserRole') BEGIN
	PRINT 'Adding ComboGroup: UserRole...'
	
	INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
	VALUES ('UserRole', 'Validation Types: S = System Administrator')

	INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
	VALUES ('UserRole', 99, 'System Administrator')
	
	INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
	VALUES ('UserRole', 99, 'S')
END

/* COMBOGROUP: Title */
IF NOT EXISTS(SELECT 1 FROM COMBOGROUP WHERE GROUPNAME = 'Title') BEGIN
	PRINT 'Adding ComboGroup: Title...'

	INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
	VALUES ('Title', 'Validation Types: O=Other, M=Male, F=Female')
	
	INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
	VALUES ('Title', 99, 'Other')
	
	INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
	VALUES ('Title', 99, 'O')
END

/* COMBOGROUP: UserAccessType */
IF NOT EXISTS(SELECT 1 FROM COMBOGROUP WHERE GROUPNAME = 'UserAccessType') BEGIN
	PRINT 'Adding ComboGroup: UserAccessType...'

	INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
	VALUES ('UserAccessType', 'Validation Types: Numeric Level of Authority')
	
	INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
	VALUES ('UserAccessType', 60, 'Head Office Underwriter')
	
	INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
	VALUES ('UserAccessType', 60, '80')
END

/* SUPERVISORUSERITEM: Organisation */
IF NOT EXISTS(SELECT 1 FROM SUPERVISORUSERITEM WHERE USERID = 'Default' AND ITEMID = 800) BEGIN
	PRINT 'Adding UserItem 800 (Organisation)...'	

	INSERT INTO SUPERVISORUSERITEMS (USERID, ITEMID)
	VALUES ('Default', 800)
END

/* SUPERVISORUSERITEM: Users */
IF NOT EXISTS(SELECT 1 FROM SUPERVISORUSERITEM WHERE USERID = 'Default' AND ITEMID = 880) BEGIN
	PRINT 'Adding UserResource 880 (Users)...'	

	INSERT INTO SUPERVISORUSERITEMS (USERID, ITEMID)
	VALUES ('Default', 880)
END

COMMIT TRANSACTION
