/*****************************************************************************/
/* File Name:	Default User Oracle Server.sql                               */
/* Description: A script to create the minimum data required to log into     */
/*		Core Supervisor with a blank Omiga4 database.                */
/*                                                                           */
/* Change History                                                            */
/* Prog	Date		Description                                          */
/* STB	24-Jan-02	Created Script                                       */
/* STB  31-Jan-02	Amended the SupervisorUserItem inserts to match the  */
/*                      spec'ed database schema.                             */
/* STB	01-Feb-02	Copied this version from the SQL-Server orginial.    */
/*****************************************************************************/

/* COUNTY */
INSERT INTO COUNTRY (COUNTRYNUMBER, COUNTRYNAME)
VALUES	(1, 'England');

/* DISTRIBUTIONCHANNEL */
INSERT INTO DISTRIBUTIONCHANNEL (CHANNELID, CHANNELNAME, COUNTRYNUMBER)
VALUES	('1', 'Default', 1);

/* DEPARTMENT */
INSERT INTO DEPARTMENT (DEPARTMENTID, DEPARTMENTNAME)
VALUES	('1', 'Default');

/* REGION */
INSERT INTO REGION (REGIONID, REGIONNAME, REGIONTYPE)
VALUES (1, 'Default', 10);

/* UNIT */
INSERT INTO UNIT (UNITID, UNITNAME)
VALUES ('Default', 'Default');

/* COMPETENCY */
INSERT INTO COMPETENCY (COMPETENCYTYPE, COMPETENCYACTIVEFROM)
VALUES ('20', TO_DATE(sysdate,'YYYY-MM-DD HH24:MI:SS'));

/* WORKINGHOURTYPE */
INSERT INTO WORKINGHOURTYPE (WORKINGHOURTYPE, WORKINGHOURTYPEDESCRIPTION)
VALUES (1, '0:00 - 23:59 Mon - Su');

/* WORKINGHOURS Sunday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 1, 'Sunday', 0, 1, 23, 59);

/* WORKINGHOURS Monday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 2, 'Monday', 0, 1, 23, 59);

/* WORKINGHOURS Tuesday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 3, 'Tuesday', 0, 1, 23, 59);

/* WORKINGHOURS Wednesday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 4, 'Wednesday', 0, 1, 23, 59);

/* WORKINGHOURS Thursday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 5, 'Thursday', 0, 1, 23, 59);

/* WORKINGHOURS Friday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 6, 'Friday', 0, 1, 23, 59);

/* WORKINGHOURS Saturday */
INSERT INTO WORKINGHOURS (WORKINGHOURTYPE, DAYOFTHEWEEK, DAYOFTHEWEEKTEXT, FROMHOUR, FROMMINUTE, TOHOUR, TOMINUTE)
VALUES (1, 7, 'Saturday', 0, 1, 23, 59);

/* OMIGAUSER */
INSERT INTO OMIGAUSER (USERID, OMIGAUSERACTIVEFROM, OMIGAUSERACTIVETO, WORKINGHOURTYPE, ACCESSTYPE)
VALUES ('Default', TO_DATE(sysdate,'YYYY-MM-DD HH24:MI:SS'), TO_DATE(ADD_MONTHS(sysdate,120), 'YYYY-MM-DD HH24:MI:SS');

/* ORGANISATIONUSER */
INSERT INTO ORGANISATIONUSER (USERID, DATEOFBIRTH, USERFORENAME, USERINITIALS, USERSURNAME, USERTITLE)
VALUES ('Default', TO_DATE(sysdate,'YYYY-MM-DD HH24:MI:SS'), 'default', 'S', 'user', 99);

/* PASSWORD (omiga4) */
INSERT INTO PASSWORD (USERID, PASSWORDVALUE, PASSWORDCREATIONDATE)
VALUES ('Default', '~Xy~H~?rS', TO_DATE(sysdate, 'YYYY-MM-DD HH24:MI:SS'));

/* USERCOMPETENCY */
INSERT INTO USERCOMPETENCY (USERID, COMPETENCYTYPE, USERCOMPETENCYACTIVEFROM, COMPETENCYTYPETEXT)
VALUES ('Default', '20', TO_DATE(sysdate, 'YYYY-MM-DD HH24:MI:SS'), '500,000 - 100 - 500,000');

/* USERROLE */
INSERT INTO USERROLE (UNITID, USERID, USERROLEACTIVEFROM, ROLE, USERROLETEXT)
VALUES ('Default', 'Default', TO_DATE(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 99, 'System Administrator');

/* COMBOGROUP: UserRole */
INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
VALUES ('UserRole', 'Validation Types: S = System Administrator');

INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
VALUES ('UserRole', 99, 'System Administrator');
	
INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
VALUES ('UserRole', 99, 'S');

/* COMBOGROUP: Title */
INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
VALUES ('Title', 'Validation Types: O=Other, M=Male, F=Female');
	
INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
VALUES ('Title', 99, 'Other');
	
INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
VALUES ('Title', 99, 'O');

/* COMBOGROUP: UserAccessType */
INSERT INTO COMBOGROUP (GROUPNAME, GROUPNOTE) 
VALUES ('UserAccessType', 'Validation Types: Numeric Level of Authority');
	
INSERT INTO COMBOVALUE (GROUPNAME, VALUEID, VALUENAME) 
VALUES ('UserAccessType', 60, 'Head Office Underwriter');
	
INSERT INTO COMBOVALIDATION (GROUPNAME, VALUEID, VALIDATIONTYPE) 
VALUES ('UserAccessType', 60, '80');

/* SUPERVISORUSERITEM: Organisation */
INSERT INTO SUPERVISORUSERITEMS (USERID, ITEMID)
VALUES ('Default', 800);

/* SUPERVISORUSERITEM: Users */
INSERT INTO SUPERVISORUSERITEMS (USERID, ITEMID)
VALUES ('Default', 880);

