Attribute VB_Name = "ODIGetAccountDetails"
'Workfile:      ODIFindAccountDetails.cls
'Copyright:     Copyright © 2001 Marlborough Stirling

'Description:
'
'Dependencies:
'Issues:        Instancing:
'               MTSTransactionMode:
'------------------------------------------------------------------------------------------
'History:
'
'Prog   Date        Description
'RF     27/08/01    Expanded class created by LD.
'------------------------------------------------------------------------------------------
Option Explicit

Public Sub FindAccountDetails( _
    ByVal objODITransformerState As ODITransformerState, _
    ByVal vxmlRequestNode As IXMLDOMNode, _
    ByVal vxmlResponseNode As IXMLDOMNode)
' header ----------------------------------------------------------------------------------
' description:
' pass:
'   vxmlRequestNode
'       XML REQUEST node
'   vxmlResponseNode
'       XML RESPONSE node
' return:
' exceptions:
'       oeRecordNotFound
'------------------------------------------------------------------------------------------
On Error GoTo FindAccountDetailsExit
    
    Const strFunctionname As String = "FindAccountDetails"
    
    ' <VSA> Visual Studio Analyser Support
    #If USING_VSA Then
        Dim VSA As New vsa_shared: VSA.Initialize (TypeName(Me) & "." & strFunctionname)
    #End If

    Dim nodeConverterResponse As IXMLDOMNode
    Dim nodeCustomer As IXMLDOMNode
    Dim nodeCustomerInvolvementShortcut As IXMLDOMNode
    Dim strCustomerNumber As String
    Dim xmlCustomerListNode As IXMLDOMNode
    
    '------------------------------------------------------------------------------------------
    ' call PlexusHomeImpl_searchByPattern_CustomerInvolvementPattern
    '------------------------------------------------------------------------------------------
    
    Set nodeCustomer = xmlGetMandatoryNode(vxmlRequestNode, "CUSTOMER")
    strCustomerNumber = xmlGetMandatoryAttributeText(nodeCustomer, "CUSTOMERNUMBER")
    
    nodeConverterResponse = _
        PlexusHomeImpl_searchByPattern_CustomerInvolvementPattern( _
            objODITransformerState, strCustomerNumber)
    
    ' parse the response
    Set nodeCustomerInvolvementShortcut = _
        nodeConverterResponse.selectNodes("RESPONSE/ARGUMENTS/MSG_ARRAY/CUSTOMERINVOLVEMENTSHORTCUT/MORTGAGEKEY")
        
    ' mortgageaccountlist response node
    Dim xmlMortgageAccountListNode As IXMLDOMNode
    Set xmlMortgageAccountListNode = vxmlResponseNode.ownerDocument.createElement("MORTGAGEACCOUNTLIST")
    vxmlResponseNode.appendChild xmlMortgageAccountListNode
       
    ' mortgage account node
    Dim nodeMortgageAccount As IXMLDOMNode
    Set nodeMortgageAccount = vxmlResponseNode.ownerDocument.createElement("MORTGAGEACCOUNT")
    'xmlSetAttributeValue nodeMortgageAccount, "MORTGAGEACCOUNT", xmlGetNodeText(xmlMorgageNode, ".//PRIMARYCUSTOMERKEY/ENTITYNUMBER/@DATA")
    'xmlSetAttributeValue nodeMortgageAccount, "SECONDCHARGEINDICATOR, """
    'xmlSetAttributeValue nodeMortgageAccount, "INDEMNITYCOMPANYNAME, """
    'xmlSetAttributeValue nodeMortgageAccount, "INDEMNITYMORTGAGEAMOUNT, """
    'xmlSetAttributeValue nodeMortgageAccount, "INDEMNITYAMOUNT, """
    'xmlSetAttributeValue nodeMortgageAccount, "LENDERCODE, """
    'xmlSetAttributeValue nodeMortgageAccount, "CREATIONDATE, """
    vxmlResponseNode.appendChild nodeMortgageAccount
        
    ' customer list node
    Set xmlCustomerListNode = vxmlResponseNode.ownerDocument.createElement("CUSTOMERLIST")
    nodeMortgageAccount.appendChild xmlCustomerListNode
      
    ' customer node
    Set nodeCustomer = vxmlResponseNode.ownerDocument.createElement("CUSTOMERLIST")
    xmlCustomerListNode.appendChild nodeCustomer
      
    ' property node
    Dim xmlPropertyNode As IXMLDOMNode
    Set xmlPropertyNode = vxmlResponseNode.ownerDocument.createElement("PROPERTY")
    nodeMortgageAccount.appendChild xmlPropertyNode
      
    ' mortgage loan list node
    Dim xmlMortgageLoanListNode As IXMLDOMNode
    Set xmlMortgageLoanListNode = vxmlResponseNode.ownerDocument.createElement("MORTGAGELOANLIST")
    nodeMortgageAccount.appendChild xmlMortgageLoanListNode
      
    ' arrears history list node
    Dim xmlArrearsHistoryListNode As IXMLDOMNode
    Set xmlArrearsHistoryListNode = vxmlResponseNode.ownerDocument.createElement("ARREARSHISTORYLIST")
    nodeMortgageAccount.appendChild xmlArrearsHistoryListNode
      
    ' if RESPONSE nodes has no child nodes,
    ' then no records found matching REQUEST criteria
    If vxmlResponseNode.hasChildNodes = False Then
        errThrowError strFunctionname, oerecordnotfound
    End If
    
FindAccountDetailsExit:

    Set nodeCustomer = Nothing
    Set xmlMortgageAccountListNode = Nothing
    Set nodeMortgageAccount = Nothing
    Set xmlCustomerListNode = Nothing
    Set xmlPropertyNode = Nothing
    Set xmlMortgageLoanListNode = Nothing
    Set nodeCustomerInvolvementShortcut = Nothing
    
    ' <VSA> Visual Studio Analyser Support
    #If USING_VSA Then
        Set VSA = Nothing
    #End If
    
    errCheckError strFunctionname

End Sub


'<!ELEMENT RESPONSE ((MESSAGE*, MORTGAGEACCOUNTLIST) | ERROR)>
'    <!ATTLIST RESPONSE TYPE (SUCCESS | WARNING | APPERR | SYSERR) #REQUIRED>
'<!ELEMENT MORTGAGEACCOUNTLIST (MORTGAGEACCOUNT+)>
'<!ELEMENT MORTGAGEACCOUNT (CUSTOMERLIST, PROPERTY, MORTGAGELOANLIST,
'                           ARREARSHISTORY?)>
'<!ATTLIST MORTGAGEACCOUNT ACCOUNTNUMBER CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT SECONDCHARGEINDICATOR CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT INDEMNITYCOMPANYNAME CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT INDEMNITYMORTGAGEAMOUNT CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT INDEMNITYAMOUNT CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT LENDERCODE CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT CREATIONDATE CDATA #REQUIRED>
'<!ELEMENT CUSTOMERLIST (CUSTOMER+)>
'<!ELEMENT CUSTOMER (CURRENTADDRESS, CORRESPONDENCEADDRESS?,
'                    TELEPHONENUMBERLIST?>
'<!ATTLIST CUSTOMER CUSTOMERNUMBER CDATA #REQUIRED>
'<!ATTLIST CUSTOMER SURNAME CDATA #REQUIRED>
'<!ATTLIST CUSTOMER FIRSTFORENAME CDATA #REQUIRED>
'<!ATTLIST CUSTOMER SECONDFORENAME CDATA #REQUIRED>
'<!ATTLIST CUSTOMER OTHERFORENAMES CDATA #REQUIRED>
'<!ATTLIST CUSTOMER TITLE CDATA #REQUIRED>
'<!ATTLIST CUSTOMER DATEOFBIRTH CDATA #REQUIRED>
'<!ATTLIST CUSTOMER GENDER CDATA #REQUIRED>
'<!ATTLIST CUSTOMER MOTHERSMAIDENNAME CDATA #REQUIRED>
'<!ATTLIST CUSTOMER CONTACTEMAILADDRESS CDATA #REQUIRED>
'<!ATTLIST CUSTOMER MARITALSTATUS CDATA #REQUIRED>
'<!ATTLIST CUSTOMER NATIONALINSURANCENUMBER CDATA #REQUIRED>
'<!ATTLIST CUSTOMER MEMBEROFSTAFF CDATA #REQUIRED>
'<!ATTLIST CUSTOMER CUSTOMERORDER CDATA #REQUIRED>
'<!ATTLIST CUSTOMER CUSTOMERROLETYPE CDATA #REQUIRED>
'<!ATTLIST CUSTOMER CHANNELID CDATA #REQUIRED>
'<!ATTLIST CUSTOMER OTHERSYSTEMTYPE CDATA #REQUIRED>
'<!ELEMENT CURRENTADDRESS>
'<!ATTLIST CURRENTADDRESS BUILDINGORHOUSENAME CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS BUILDINGORHOUSENUMBER CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS FLATNUMBER CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS STREET CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS DISTRICT CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS TOWN CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS COUNTY CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS COUNTRY CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS POSTCODE CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS DELIVERYPOINTSUFFIX CDATA #REQUIRED>
'<!ATTLIST CURRENTADDRESS MAILSORTCODE CDATA #REQUIRED>
'<!ELEMENT CORRESPONDENCEADDRESS>
'<!ATTLIST CORRESPONDENCEADDRESS BUILDINGORHOUSENAME CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS BUILDINGORHOUSENUMBER CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS FLATNUMBER CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS STREET CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS DISTRICT CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS TOWN CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS COUNTY CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS COUNTRY CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS POSTCODE CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS DELIVERYPOINTSUFFIX CDATA #REQUIRED>
'<!ATTLIST CORRESPONDENCEADDRESS MAILSORTCODE CDATA #REQUIRED>
'<!ELEMENT TELEPHONENUMBERLIST (TELEPHONENUMBERDETAILS+)>
'<!ELEMENT TELEPHONENUMBERDETAILS>
'<!ATTLIST TELEPHONENUMBERDETAILS USAGE CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS COUNTRYCODE CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS AREACODE CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS TELEPHONENUMBER CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS EXTENSIONNUMBER CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS CONTACTTIME CDATA #REQUIRED>
'<!ATTLIST TELEPHONENUMBERDETAILS PREFERREDMETHODOFCONTACT CDATA #REQUIRED>
'<!ELEMENT PROPERTY (PROPERTYADDRESS)>
'<!ATTLIST MORTGAGEACCOUNT PURCHASEPRICE CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT VALUATIONDATE CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT VALUATIONAMOUNT CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT VALUERID CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT PROPERTYDESCRIPTION CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT YEARBUILT CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT PROPERTYTENURE CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT BUILDINGSSUMINSURED CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT REINSTATEMENTAMOUNT CDATA #REQUIRED>
'<!ATTLIST MORTGAGEACCOUNT HOMEINSURANCETYPE CDATA #REQUIRED>
'<!ELEMENT PROPERTYADDRESS>
'<!ATTLIST PROPERTYADDRESS BUILDINGORHOUSENAME CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS BUILDINGORHOUSENUMBER CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS FLATNUMBER CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS STREET CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS DISTRICT CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS TOWN CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS COUNTY CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS COUNTRY CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS POSTCODE CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS DELIVERYPOINTSUFFIX CDATA #REQUIRED>
'<!ATTLIST PROPERTYADDRESS MAILSORTCODE CDATA #REQUIRED>
'<!ELEMENT MORTGAGELOANLIST (MORTGAGELOAN+)>
'<!ELEMENT LOAN>
'<!ATTLIST MORTGAGELOAN ACCOUNTNUMER CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN LOANACCOUNTNUMER CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN MORTGAGEPRODUCTCODE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN MORTGAGEPRODUCTDESCRIPTION CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN INTERESTRATE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN INTERESTRATETYPE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN PURPOSEOFLOAN CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN OUTSTANDINGBALANCE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN REPAYMENTTTYPE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN ORIGINALLOANAMOUNT CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN MONTHLYREPAYMENT CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN ORIGINALTERMYEARS CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN ORIGINALTERMMONTHS CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN STARTDATE CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN REDEMPTIONSTATUS CDATA #REQUIRED>
'<!ATTLIST MORTGAGELOAN REDEMPTIONDATE CDATA #REQUIRED>
'<!ELEMENT ARREARSHISTORY>
'<!ATTLIST ARREARSHISTORY MAXIMUMBALANCE CDATA #REQUIRED>
'<!ATTLIST ARREARSHISTORY MAXIMUMNUMBEROFMONTHS CDATA #REQUIRED>
'<!ATTLIST ARREARSHISTORY DATECLEARED CDATA #REQUIRED>
'<!ATTLIST ARREARSHISTORY DESCRIPTIONOFLOAN CDATA #REQUIRED>
'<!ELEMENT ERROR (NUMBER, SOURCE, DESCRIPTION)>
'<!ELEMENT NUMBER (#PCDATA)>
'<!ELEMENT SOURCE (#PCDATA)>
'<!ELEMENT DESCRIPTION (#PCDATA)>
'<!ELEMENT MESSAGE (MESSAGETEXT, MESSAGETYPE)>
'<!ELEMENT MESSAGETEXT (#PCDATA)>
'<!ELEMENT MESSAGETYPE (#PCDATA)>
'
