//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// History
// HMA  21/05/2006	MAR1820 Set Keep Alive = False
// AS	06/06/2006	MAR1862 Add configuration of web requests
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Vertex.Fsd.Omiga.omFDM.PinMailerFulfilmentRequest 
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using System.Net;
	using System.Reflection;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectGatewaySoapBinding", Namespace="http://interfaces")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericRequestType))]
    public class DirectGatewaySoapServiceWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
		// MAR1820
		private static PropertyInfo requestPropertyInfo = null; 

		protected override System.Net.WebRequest GetWebRequest(Uri uri) 
		{ 
			WebRequest request = base.GetWebRequest(uri); 

			if (requestPropertyInfo==null) 
				// Retrieve property info and store it in a static member for optimizing future use 
				requestPropertyInfo = request.GetType().GetProperty("Request"); 

			// Retrieve underlying web request 
			HttpWebRequest webRequest = 
				(HttpWebRequest)requestPropertyInfo.GetValue(request,null); 

			// Setting KeepAlive 
			webRequest.KeepAlive = false; 
			return request; 
		} 

        /// <remarks/>
        public DirectGatewaySoapServiceWse() {
            this.Url = "http://rdgsmarsdgw1/DGWWebServices/services/DirectGatewaySoapEndpoint";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="request", RequestNamespace="http://interfaces", ResponseElementName="response", ResponseNamespace="http://interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProcessPinMailerFulfilmentResponse", Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")]
        public ProcessPinMailerFulfilmentResponseType execute([System.Xml.Serialization.XmlElementAttribute(Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")] ProcessPinMailerFulfilmentRequestType ProcessPinMailerFulfilmentRequest) {
            object[] results = this.Invoke("execute", new object[] {
                        ProcessPinMailerFulfilmentRequest});
            return ((ProcessPinMailerFulfilmentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexecute(ProcessPinMailerFulfilmentRequestType ProcessPinMailerFulfilmentRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("execute", new object[] {
                        ProcessPinMailerFulfilmentRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProcessPinMailerFulfilmentResponseType Endexecute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProcessPinMailerFulfilmentResponseType)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectGatewaySoapBinding", Namespace="http://interfaces")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericRequestType))]
    public class DirectGatewaySoapService : Vertex.Fsd.Omiga.Core.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DirectGatewaySoapService() {
            this.Url = "http://rdgsmarsdgw1/DGWWebServices/services/DirectGatewaySoapEndpoint";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="request", RequestNamespace="http://interfaces", ResponseElementName="response", ResponseNamespace="http://interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProcessPinMailerFulfilmentResponse", Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")]
        public ProcessPinMailerFulfilmentResponseType execute([System.Xml.Serialization.XmlElementAttribute(Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")] ProcessPinMailerFulfilmentRequestType ProcessPinMailerFulfilmentRequest) {
            object[] results = this.Invoke("execute", new object[] {
                        ProcessPinMailerFulfilmentRequest});
            return ((ProcessPinMailerFulfilmentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexecute(ProcessPinMailerFulfilmentRequestType ProcessPinMailerFulfilmentRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("execute", new object[] {
                        ProcessPinMailerFulfilmentRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProcessPinMailerFulfilmentResponseType Endexecute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProcessPinMailerFulfilmentResponseType)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")]
    public class ProcessPinMailerFulfilmentRequestType : GenericRequestType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generic.dg.ingdirect.com/0.0.1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessPinMailerFulfilmentRequestType))]
    public abstract class GenericRequestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientDevice;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TellerID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TellerPwd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ProxyID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ProxyPwd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Operator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ProductType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SessionID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CommunicationChannel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CommunicationDirection;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ServiceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerNumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generic.dg.ingdirect.com/0.0.1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessPinMailerFulfilmentResponseType))]
    public abstract class GenericResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ErrorMessage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerNumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://processpinmailerfulfilment.fulfilment.services.dg.ingdirect.com/0.0.1")]
    public class ProcessPinMailerFulfilmentResponseType : GenericResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PinMailerFulfilmentResponse;
    }
}
