/*
--------------------------------------------------------------------------------------------
Workfile:			errConstants.cs
Copyright:			Copyright © 2007 Marlborough Stirling
Description:		Header file for Omiga error numbers.
--------------------------------------------------------------------------------------------
History:

Prog	Date		Description
IK	  01/11/2000	Initial creation
ASm	 10/01/2001	SYS1817: Rationalisation of methods following meeting with PC and IK
DJP	 12/03/2001	SYS1839 added oeObjectNotCreatable
DM	  19/09/2001	SYS2716 added oeInvalidMessageQueueType
JR	  27/05/2002	SYS4639 Changed oeObjectNotCreatable message# from 563 to 576
AC	  14/04/2004	BBG196 - added new constant for PLOM user verification
--------------------------------------------------------------------------------------------
.Net Specific History:

Prog	Date		Description
AS		09/05/2007	First .Net version. Ported from errConstants.bas.
--------------------------------------------------------------------------------------------
*/
using System;

// Missing XML comment for publicly visible type or member.
#pragma warning disable 1591

namespace Vertex.Fsd.Omiga.VisualBasicPort.Assists
{
	/// <summary>
	/// System wide Omiga errors. Each error matches a record on the MESSAGE table, where 
	/// MESSAGE.MESSAGENUMBER = the enum constant.
	/// </summary>
	/// <remarks>
	/// This enum should not be used for Omiga application component errors. Use consecutive errors 
	/// numbers from 500+.
	/// </remarks>
	public enum OMIGAERROR
	{
		UnspecifiedError = errConstants.vbObjectError + 512 + 999,

		InvalidCheckDigitNumber = 1,
		InvalidNumberType = 2,
		InvalidGlobalParameter = 3,
		MissingPostCode = 100,
		MissingSurnameAndForename = 101,
		MissingSurnameDateofBirth = 102,
		InvalidLockType = 103,
		InvalidSearchString = 104,
		MissingCustomerNumberAndCustomerVersionNumber = 105,
		MissingUserId = 106,
		InvalidDatabaseError = 107,
		MissingComboGroup = 108,
		MissingComboValueId = 109,
		PafAddressUnsuccessful = 110,
		UnauthorisedUnit = 111,
		InvalidLogon = 112,
		InvalidPassword = 113,
		UnauthorisedFunctionalArea = 114,
		MissingAccess = 115,
		UnauthorisedHours = 116,
		MaximumAccessExceeded = 117,
		CompletenessCheckFailed = 119,
		InsufficientPafDetails = 120,
		QuickQuoteNotAvailable = 121,
		QuickQuoteDetailsMissing = 122,
		QuickQuoteApplicantDetailsMissing = 123,
		QuickQuoteOutgoingsDetailsmissing = 124,
		QuickQuotePersonalDebtsDetailsmissing = 125,
		AttitudeToBorrowingDetailsmissing = 126,
		MissingApplicants = 127,
		MissingTelephoneNumber = 128,
		InvalidInterestOnlyAmount = 129,
		TermofLoanOutOfRange = 130,
		InvalidAmountRequested = 131,
		InvalidFurtherFilteringCriteria = 132,
		CustomerAlreadyLinkedToPackage = 133,
		AddressTypeRecordAlreadyExists = 134,
		InvalidMovedInDate = 135,
		MissingCompanyId = 136,
		MissingSurnameFirstForename = 137,
		InvalidCustomerRole = 138,
		CustomerAlreadyLinkedToApplication = 139,
		InvalidDischargeDate = 140,
		InvalidPartandPartInterestOnlyAmount = 141,
		MaximumPortedLoans = 142,
		MissingAddressFields = 143,
		InvalidPasswordLength = 144,
		InvalidPasswordNotUnique = 145,
		MortgageAccountStillAttached = 146,
		MissingBankCreditCard = 147,
		MissingLifeProduct = 148,
		MissingDeclinedMortgage = 149,
		MissingArrearsHistory = 150,
		MissingLoanLiability = 151,
		MissingCCJHistory = 152,
		MissingBankruptcyHistory = 153,
		MissingAdditionalCardHolders = 154,
		MissingOthersLoanLiability = 155,
		MissingOthersLifeProduct = 156,
		MissingOthersDeclinedMortgage = 157,
		MissingOthersArrearsHistory = 158,
		MissingOthersCCJHistory = 159,
		InvalidJudgementDate = 160,
		InvalidEndDate = 161,
		InvalidDate = 162,
		MissingAmountRequestedPurchasePrice = 163,
		InvalidCustomerAgeMinimum = 164,
		InvalidCustomerAgeMaximum = 165,
		InvalidNameFirstCharacter = 166,
		CannotReorderCustomer = 168,
		CannotRemoveSoleApplicant = 169,
		MissingCustomerNumber = 170,
		CannotRemoveSoleApplicantFromPackage = 171,
		MissingLoanSplit = 172,
		InvalidNumberOfApplicants = 173,
		InvalidNumberOfApplicantsMaximum = 174,
		InvalidNumberOfCustomersMaximum = 175,
		InvalidNumberOfGuarantorsMaximum = 176,
		CannotRecalculateOneOffCosts = 177,
		InvalidNumberOfLoans = 179,
		InsuffientUserMandate = 180,
		InvalidValuationDate = 181,
		ApplicationAlreadyLocked = 182,
		ApplicantAlreadyLocked = 183,
		InvalidSubQuote = 184,
		ApplicantsWithSameOrderNumber = 185,
		ApplicantsNotConsecutive = 186,
		CannotReservePortedMortgageProduct = 189,
		CustomerAlreadyLocked = 190,
		MaximumLoanComponents = 191,
		MissingOutstandingLoanAmount = 192,
		InvalidMortgageProduct = 193,
		IncentivesNotApplicable = 194,
		MissingLoanComponentDetails = 195,
		InvalidLoadTotal = 196,
		InvalidRepaymentType = 197,
		MissingMortgageProductDetails = 198,
		InvalidQuotationRecommendation = 199,
		QuotationAlreadyRecommended = 200,
		InvalidQuotationRecommendationNotAffordable = 201,
		InvalidQuotationsAcceptance = 202,
		QuotationAlreadyAccepted = 203,
		ShowAllProductsWithoutChecksNotAvailable = 205,
		PortedLoanComponentsCannotBeEdited = 206,
		UnableToCalculateMortgageRepayments = 207,
		MissingRepaymentType = 208,
		MissingCustomerAddressKey = 209,
		MissingCountryOfOriginLanguage = 210,
		MissingPartAndPartSplit = 211,
		MissingMortgageProductSelectionVersion = 212,
		MissingMortgageProductMaximumNumberOfRecords = 213,
		InvalidJudgementDateDateCleared = 214,
		SelectedquotationAlreadyActive = 215,
		SelectedQuotationCannotBeReinstated = 216,
		MissingMortgageDetails = 218,
		InvalidPastDate = 219,
		MissingApplicantForMortgage = 220,
		MissingOthersForMortgage = 221,
		CalculationsEngineInterface = 222,
		MissingIncentives = 223,
		MissingMortgageSubQuote = 224,
		InvalidBandCProduct = 225,
		QuotationValidation = 226,
		CreatingNewQuotation = 227,
		MissingPaymentProtectionSubQuoteDetails = 228,
		InvalidTotalCoverAmount = 229,
		InvalidSumOfApplicantCoverAmounts = 231,
		MissingPaymentProtectionRates = 232,
		MissingPassword = 233,
		InvalidNewPassword = 234,
		Polaris = 235,
		PolarisDecline = 236,
		PolarisRefer = 237,
		InvalidLoanComponentTerm = 238,
		MissingDataForSummaryDetails = 239,
		InvalidMortgageSubQuote = 240,
		MissingEmploymentType = 241,
		MissingEmploymentStatus = 242,
		MissingJobTitle = 243,
		MissingAmount = 244,
		MissingPaymentFrequency = 245,
		MissingAccountancyFirmName = 246,
		MissingNetProfitYearAmount = 247,
		MissingNetProfitYear = 248,
		MissingOtherIncomeType = 249,
		AffordabilityNotAvailable = 251,
		MissingOtherIncomeAmount = 252,
		MissingOtherIncomeFrequency = 253,
		MissingIntermediaryRecord = 254,
		PortedLoanAlreadyExists = 255,
		InsufficientSearchCriteria = 256,
		MissingSurname = 257,
		InvalidThirdParty = 258,
		MissingCompanyName = 259,
		MissingPanelId = 260,
		PanelDirectory = 261,
		InvalidAdditionalDetails = 262,
		MissingGroupConnectionAccountType = 263,
		InvalidAliasName = 264,
		MissingAliasType = 265,
		MissingTenancyType = 266,
		InvalidMortgageProductSelectionVersion = 267,
		InvalidNewPasswordFormatAllSame = 268,
		InvalidNewPasswordFormatNoUpperCase = 269,
		InvalidNewPasswordFormatNoLowerCase = 270,
		InvalidNewPasswordFormatNoNumeric = 271,
		InvalidNewPasswordFormatNoSpecial = 272,
		InvalidNewPasswordFormatNoUserId = 273,
		InvalidClearedDate = 274,
		MissingMortgageProductDataVersion = 275,
		CurrentCreditCheck = 276,
		InvalidEquityAmount = 277,
		DuplicateNetProfitYearsEnding = 278,
		InvalidNetProfitYearEnding = 279,
		MissingCreditCheckDetails = 280,
		MissingLTV = 281,
		CreditCheckInterfaceUnavailable = 282,
		InvalidDateofBirth = 283,
		InvalidLeaseStartDate = 284,
		InvalidYearBuiltDate = 285,
		InvalidTelephoneNumber = 286,
		InvalidRedemptionDate = 287,
		InvalidRenewalDate = 288,
		InvalidProductStructure = 289,
		MissingLoanComponents = 290,
		MissingGlobalParameter = 291,
		InvalidContactHistoryDetails = 292,
		VotersRollDetails = 293,
		NoticeOfCorrectionDetails = 294,
		CustomerAddressDetails = 295,
		PublicInformationDetails = 296,
		CAISDetails = 297,
		CIFASDetails = 298,
		CAPSDetails = 299,
		AliasAndAssociationsDetails = 300,
		UserAlreadyOwnsApplication = 301,
		OtherSystemCustomerNumber = 302,
		BatchScheduleHasFinished = 304,
		BatchStatus = 305,
		BatchJobLaunch = 306,
		NoAcceptedQuote = 308,
		ValuerInstructionMissingPaymentDetails = 309,
		ValuerInstructionApplicationLocked = 310,
		ValuerInstructionLockingApplication = 311,
		ValuerInstructionInvalidInvoiceAmount = 312,
		ValuerInstructionCreatingTask = 313,
		ValuerInstructionDeletingLock = 314,
		ValuerInstructionUpdatingInstruction = 315,
		LedgerCodes = 316,
		RecordNotFound = 500,
		XMLParserError = 502,
		InvalidKeyString = 503,
		NoAfterImagePresent = 504,
		CommandFailed = 505,
		MissingPrimaryTag = 506,
		InvalidParameter = 507,
		DuplicateKey = 508,
		NoDataForCreate = 509,
		NoDataForUpdate = 510,
		ArrayLimitExceeded = 511,
		NoRowsAffected = 512,
		InvalidNoOfRows = 513,
		InternalError = 514,
		MissingFieldDesc = 515,
		MissingTableDesc = 516,
		MissingTypeDesc = 517,
		MissingElementValue = 518,
		MissingElement = 519,
		MissingKeyDesc = 520,
		MissingUpdateSet = 521,
		MissingTableName = 522,
		MissingXMLTableName = 523,
		MissingKey = 524,
		NoRowsAffectedByDeleteAll = 525,
		InValidKeyValue = 526,
		InValidDataTypeValue = 527,
		InValidKey = 528,
		NoFieldsFound = 529,
		NoFieldItemFound = 530,
		NoFieldItemName = 531,
		NoComboTagValue = 532,
		InvalidDateTimeFormat = 533,
		NoBeforeImagePresent = 534,
		ChildRecordsFound = 535,
		InvalidSearchString2 = 551,
		MTSNotFound = 555,
		UnableToConnect = 556,
		MissingParameter = 557,
		XMLMissingElement = OMIGAERROR.MissingElement,
		XMLMissingElementText = OMIGAERROR.MissingElementValue,
		XMLMissingAttribute = 558,
		XMLInvalidAttributeValue = 559,
		XMLMissingPrimaryKey = 560,
		XMLInvalidRequestNode = 561,
		XMLAttributeAlreadyExists = 562,
		ObjectNotCreatable = 576,
		SchemaNotLoaded = 800,
		SchemaParseError = 801,
		NotImplemented = 900,
		InvalidMessageNo = 901,
		InvalidMessageQueueType = 902,
		InvalidPLOMUserLevel = 10002,
	}

	public enum OMIGAERRORTYPE 
	{
		omWARNING,
		omNO_ERR,
	}

	public enum MESSAGE 
	{
		omMESSAGE_TEXT,
		omMESSAGE_TYPE,
	}

	public enum ERRORS 
	{
		eNOTMIPLEMENTED = errConstants.vbObjectError + 512,
		eXMLMISSINGELEMENT,
		eXMLMISSINGATTRIBUTE,
		eXMLINVALIDATTTRIBUTE,
		eXMLINVALIDATTTRIBUTEVALUE,
		eRECORDNOTFOUND,
		eUNSPECIFIEDERROR = errConstants.vbObjectError + 512 + 999,
		eFAILEDTOLOADREQUEST = errConstants.vbObjectError + 512 + 1,
	}

	public class errConstants
	{
		public const int vbObjectError = -2147221504;
		public const int clngMAX_ERROR_NO = 10000;
		public const int clngADO_START_ERROR_NO = 3000;
		public const int clngADO_END_ERROR_NO = 3999;
	}
}
