VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IApplicationThirdPartyDO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Sub CreateArchitect(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub CreateBankBuildingSociety(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub CreateBuilder(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub CreateEstateAgent(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub CreateLegalRep(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub DeleteArchitect(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub DeleteBankBuildingSociety(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub DeleteBuilder(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub DeleteEstateAgent(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub DeleteLegalRep(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Function FindBankBuildingSocietyList(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function FindApplicationThirdPartyList(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function GetArchitect(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function GetBankBuildingSociety(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function GetBuilder(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function GetEstateAgent(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Function GetLegalRep(ByVal vxmlTableElement As IXMLDOMElement) As IXMLDOMNode
End Function

Public Sub UpdateArchitect(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub UpdateBankBuildingSociety(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub UpdateBuilder(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub UpdateEstateAgent(ByVal vxmlTableElement As IXMLDOMElement)
End Sub

Public Sub UpdateLegalRep(ByVal vxmlTableElement As IXMLDOMElement)
End Sub




