//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.Fsd.Omiga.Web.Services.BrokerRegAndMaintainWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATIONUSERCONTACTDETAILS_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PASSWORD_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATIONUSER_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ARFIRM_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FIRMPERMISSIONS_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PRINCIPALFIRM_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INTRODUCERFIRM_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INTRODUCERDETAILS_base))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REQUEST_attribs_base))]
    public abstract class OmigaBrokerRegAndMaintain : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.BrokerRegAndMaintain.BrokerRegistration.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
        public abstract RESPONSEType BrokerRegistration([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")] BROKERREGISTER_REQUESTType BROKERREGISTER_REQUEST);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.BrokerRegAndMaintain.UpdateBrokerProfile.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
        public abstract RESPONSEType UpdateBrokerProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")] UPDATEBROKERPROFILE_REQUESTType UPDATEBROKERPROFILE_REQUEST);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.BrokerRegAndMaintain.GetBrokerProfile.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
        public abstract RESPONSEType GetBrokerProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")] GETBROKERPROFILE_REQUESTType GETBROKERPROFILE_REQUEST);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    public class BROKERREGISTER_REQUESTType : REQUEST_attribs_base {
        
        /// <remarks/>
        public INTRODUCERDETAILSType INTRODUCER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("CREATE")]
        public string CRUD_OP = "CREATE";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("BROKER_REGISTER")]
        public string ENTITY_REF = "BROKER_REGISTER";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCPROGID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCREF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("BrokerRegistration")]
        public string WSINTERFACEMETHOD = "BrokerRegistration";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class INTRODUCERDETAILSType : INTRODUCERDETAILS_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTRODUCERFIRM")]
        public INTRODUCERFIRMType[] INTRODUCERFIRM;
        
        /// <remarks/>
        public ORGANISATIONUSERType ORGANISATIONUSER;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class INTRODUCERFIRMType : INTRODUCERFIRM_base {
        
        /// <remarks/>
        public PRINCIPALFIRMType PRINCIPALFIRM;
        
        /// <remarks/>
        public ARFIRMType ARFIRM;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class PRINCIPALFIRMType : PRINCIPALFIRM_base {
        
        /// <remarks/>
        public FIRMPERMISSIONSType FIRMPERMISSIONS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class FIRMPERMISSIONSType : FIRMPERMISSIONS_base {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FIRMPERMISSIONSType))]
    public class FIRMPERMISSIONS_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTIVITYID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FRMPERMISSIONS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FRMPERMISSIONSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EFFECTIVEDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum msgCrudOp {
        
        /// <remarks/>
        CREATE,
        
        /// <remarks/>
        UPDATE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLPARAMType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DIRECTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLCOMMANDType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SQLPARAM")]
        public SQLPARAMType[] SQLPARAM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMMANDTEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public SQLCOMMANDType SQLCOMMAND;
        
        /// <remarks/>
        public string COMPONENT_ID;
        
        /// <remarks/>
        public string COMPONENT_RESPONSE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    public class RESPONSEType {
        
        /// <remarks/>
        public INTRODUCERDETAILSType INTRODUCER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class CONTACTTELEPHONEDETAILSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTDETAILSGUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TELEPHONESEQNUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TELEPHONESEQNUMSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int USAGE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USAGESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EXTENSIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class CONTACTDETAILSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTACTTELEPHONEDETAILS")]
        public CONTACTTELEPHONEDETAILSType[] CONTACTTELEPHONEDETAILS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTDETAILSGUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTFORENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTSURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTTITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CONTACTTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CONTACTTYPESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EMAILADDRESS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONEEXTENSIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATIONUSERCONTACTDETAILSType))]
    public class ORGANISATIONUSERCONTACTDETAILS_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTACTDETAILSGUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class ORGANISATIONUSERCONTACTDETAILSType : ORGANISATIONUSERCONTACTDETAILS_base {
        
        /// <remarks/>
        public CONTACTDETAILSType CONTACTDETAILS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PASSWORDType))]
    public class PASSWORD_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORDVALUE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORDCREATIONDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class PASSWORDType : PASSWORD_base {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ORGANISATIONUSERType))]
    public class ORGANISATIONUSER_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATEOFBIRTH;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EMERGENCYPASSWORD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MOTHERSMAIDENNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERFORENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERINITIALS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERSURNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int USERTITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class ORGANISATIONUSERType : ORGANISATIONUSER_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PASSWORD")]
        public PASSWORDType[] PASSWORD;
        
        /// <remarks/>
        public ORGANISATIONUSERCONTACTDETAILSType ORGANISATIONUSERCONTACTDETAILS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ARFIRMType))]
    public class ARFIRM_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FSAARFIRMREF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARFIRMNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIRMSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STATUSDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LISTINGSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LISTINGSTATUSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE5;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE6;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string POSTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONECOUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONEAREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXCOUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXAREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDBY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    public class ARFIRMType : ARFIRM_base {
        
        /// <remarks/>
        public FIRMPERMISSIONSType FIRMPERMISSIONS;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PRINCIPALFIRMType))]
    public class PRINCIPALFIRM_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FSAREF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIRMSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LISTINGSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LISTINGSTATUSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FIRMLEGALSTATUSTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FIRMLEGALSTATUSTYPESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FIRMTYPECODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FIRMTYPECODESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BANKACCOUNTNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BANKACCOUNTNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BANKACCOUNTBRANCHNAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BANKSORTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool BANKWIZARDINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BANKWIZARDINDICATORSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE5;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ADDRESSLINE6;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string POSTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONECOUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONEAREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEPHONENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXCOUNTRYCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXAREACODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAXNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STATUSDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single AGREEDPROCFEERATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGREEDPROCFEERATESpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Single VOLPROCFEEADJUSTMENT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VOLPROCFEEADJUSTMENTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool PROCLOADINGIND;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PROCLOADINGINDSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDBY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PACKAGERINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PACKAGERINDICATORSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PAYMENTMETHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PAYMENTMETHODSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INTRODUCERFIRMType))]
    public class INTRODUCERFIRM_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTRODUCERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTRODUCERFIRMSEQNO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntroducerDetail.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INTRODUCERDETAILSType))]
    public class INTRODUCERDETAILS_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTRODUCERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NATIONALINSURANCENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EMAILADDRESS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTRODUCERTYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int INTRODUCERSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTRODUCERSTATUSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LISTINGSTATUS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LISTINGSTATUSSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short ARINDICATOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ARINDICATORSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BUILDINGORHOUSENAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BUILDINGORHOUSENUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FLATNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STREET;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DISTRICT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TOWN;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COUNTY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int COUNTRY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COUNTRYSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string POSTCODE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NUMBEROFLOGINFAILURES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMBEROFLOGINFAILURESSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MARKETINGDATAOPTOUT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MARKETINGDATAOPTOUTSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LASTUPDATEDBY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public msgCrudOp CRUD_OP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRUD_OPSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    public class GETBROKERPROFILE_REQUESTTypeINTRODUCER {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTRODUCERID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BROKERREGISTER_REQUESTType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UPDATEBROKERPROFILE_REQUESTType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GETBROKERPROFILE_REQUESTType))]
    public class REQUEST_attribs_base {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    public class UPDATEBROKERPROFILE_REQUESTType : REQUEST_attribs_base {
        
        /// <remarks/>
        public INTRODUCERDETAILSType INTRODUCER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("IUPDATE")]
        public string CRUD_OP = "IUPDATE";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("BROKER_PROFILE")]
        public string ENTITY_REF = "BROKER_PROFILE";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCPROGID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCREF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("UpdateBrokerProfile")]
        public string WSINTERFACEMETHOD = "UpdateBrokerProfile";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.BrokerRegAndMaintain.Omiga.vertex.co.uk")]
    public class GETBROKERPROFILE_REQUESTType : REQUEST_attribs_base {
        
        /// <remarks/>
        public GETBROKERPROFILE_REQUESTTypeINTRODUCER INTRODUCER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("READ")]
        public string CRUD_OP = "READ";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("BROKER_PROFILE")]
        public string ENTITY_REF = "BROKER_PROFILE";
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCPROGID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREPROCREF;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("GetBrokerProfile")]
        public string WSINTERFACEMETHOD = "GetBrokerProfile";
    }
}
