VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IComboDO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'------------------------------------------------------------------------------------------
'BBG Specific History:
'
'Prog  Date     Description
'SR    13/04/04 BBG132 - New method GetRegSaleRelatedComboList
'------------------------------------------------------------------------------------------

Public Function GetQuickQuoteLocationValueId() As String
End Function
Public Function GetQuickQuoteValuationTypeValueId() As String
End Function
Public Function GetDormantLegalFeeValueId() As String
End Function
Public Function GetRegSaleRelatedComboList(ByVal vxmlElement As IXMLDOMElement) As IXMLDOMNode

End Function


