VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IAppTPClassDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function LoadArchitectData() As FreeThreadedDOMDocument40
End Function

Public Function LoadBankBuildingSocietyData() As FreeThreadedDOMDocument40
End Function

Public Function LoadBuilderData() As FreeThreadedDOMDocument40
End Function

Public Function LoadEstateAgentData() As FreeThreadedDOMDocument40
End Function

Public Function LoadLegalRepData() As FreeThreadedDOMDocument40
End Function

