VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IPackageManagerBO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public Function CreateCustomerPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function DeleteCustomerPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function ValidateCustomerPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function FindCustomerPackageList(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function CreateApplicationPackage(ByVal vxmlRequest As IXMLDOMElement, _
                                        ByVal vxmlGeneratedKeys As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function UpdateApplicationPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function ValidateApplicationPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function GetApplicationPackageData(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function CreatePackageAndApplication(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function AddCustomerToPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function
Public Function DeleteCustomerFromPackage(ByVal vxmlRequest As IXMLDOMElement) As IXMLDOMNode

End Function

