<?xml version="1.0" encoding="UTF-8"?>
<!--==============================XML Document Control=============================
Description: FindMortgageProducts WSDL

History:

Version Author      Date       Description
01.00   Ikemp    	25/07/2005 Created.   
01.01	SR			19/09/2006 EP2_1 - Modified namespaces for Epsom.
================================================================================-->
<wsdl:definitions 
	targetNamespace="http://FindMortgageProducts.Omiga.vertex.co.uk" 
    xmlns="http://FindMortgageProducts.Omiga.vertex.co.uk" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:msgRequest="http://Request.FindMortgageProducts.Omiga.vertex.co.uk" 
    xmlns:msgResponse="http://Response.FindMortgageProducts.Omiga.vertex.co.uk"  >
    <wsdl:types>
        <xs:schema 
            xmlns:msgRequest="http://Request.FindMortgageProducts.Omiga.vertex.co.uk" 
            xmlns:msgResponse="http://Response.FindMortgageProducts.Omiga.vertex.co.uk" >
            <xs:import 
                namespace="http://Request.FindMortgageProducts.Omiga.vertex.co.uk" 
                schemaLocation="FindMortgageProductsRequest.xsd" />
            <xs:import 
                namespace="http://Response.FindMortgageProducts.Omiga.vertex.co.uk" 
                schemaLocation="FindMortgageProductsResponse.xsd" />
        </xs:schema>
    </wsdl:types>
    
    <wsdl:message name="FindMortgageProductsRequestSoapIn">
        <wsdl:part name="request" element="msgRequest:REQUEST" />
    </wsdl:message>
    <wsdl:message name="FindMortgageProductsRequestSoapOut">
        <wsdl:part name="response" element="msgResponse:RESPONSE" />
    </wsdl:message>

    <wsdl:portType name="FindMortgageProductsPort">
        <wsdl:operation name="findMortgageProducts">
            <wsdl:input message="FindMortgageProductsRequestSoapIn" />
            <wsdl:output message="FindMortgageProductsRequestSoapOut" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="OmigaSoapRpcSoap" type="FindMortgageProductsPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="findMortgageProducts">
             <soap:operation 
                soapAction="http://Request.FindMortgageProducts.Omiga.vertex.co.uk" 
                style="document" />
             <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="OmigaFindMortgageProducts">
        <wsdl:port name="FindMortgageProductsPort" binding="OmigaSoapRpcSoap">
            <soap:address location="http://localhost/OmigaWebServices/FindMortgageProductsWS/OmigaFindMortgageProductsService.asmx" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
