//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace Vertex.Fsd.Omiga.Web.Services.AssignCaseToPackagerWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBindingAttribute(Name="OmigaSoapRpcSoap", Namespace="http://AssignCaseToPackager.Omiga.vertex.co.uk")]
    public abstract class OmigaAssignCaseToPackager : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Request.AssignCaseToPackager.Omiga.vertex.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RESPONSE", Namespace="http://Response.AssignCaseToPackager.Omiga.vertex.co.uk")]
        public abstract ASSIGNCASETOPACKAGERRESPONSEType assignCaseToPackager([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Request.AssignCaseToPackager.Omiga.vertex.co.uk")] ASSIGNCASETOPACKAGERREQUESTType REQUEST);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.AssignCaseToPackager.Omiga.vertex.co.uk")]
    public class ASSIGNCASETOPACKAGERREQUESTType {
        
        /// <remarks/>
        public ASSIGNCASETOPACKAGERASSIGNCASEType ASSIGNCASE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MACHINEID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CHANNELID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERAUTHORITYLEVEL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PASSWORD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Request.AssignCaseToPackager.Omiga.vertex.co.uk")]
    public class ASSIGNCASETOPACKAGERASSIGNCASEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string APPLICATIONNUMBER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRINCIPALFIRMID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string USERID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UNITID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLPARAMType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DIRECTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class SQLCOMMANDType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SQLPARAM")]
        public SQLPARAMType[] SQLPARAM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMMANDTEXT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class ERRORType {
        
        /// <remarks/>
        public long NUMBER;
        
        /// <remarks/>
        public string SOURCE;
        
        /// <remarks/>
        public string VERSION;
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string REQUEST;
        
        /// <remarks/>
        public string REQUESTDOC;
        
        /// <remarks/>
        public string REQUESTNODE;
        
        /// <remarks/>
        public string SCHEMAMASTERNODE;
        
        /// <remarks/>
        public string SCHEMAREFNODE;
        
        /// <remarks/>
        public SQLCOMMANDType SQLCOMMAND;
        
        /// <remarks/>
        public string COMPONENT_ID;
        
        /// <remarks/>
        public string COMPONENT_RESPONSE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public class MESSAGEType {
        
        /// <remarks/>
        public string MESSAGETEXT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGETYPE")]
        public string[] MESSAGETYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Response.AssignCaseToPackager.Omiga.vertex.co.uk")]
    public class ASSIGNCASETOPACKAGERRESPONSEType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE")]
        public MESSAGEType[] MESSAGE;
        
        /// <remarks/>
        public ERRORType ERROR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RESPONSEAttribType TYPE;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msgtypes.Omiga.vertex.co.uk")]
    public enum RESPONSEAttribType {
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        SYSERR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        APPERR,
    }
}
