Attribute VB_Name = "ErrorConstants"
Option Explicit

Public Enum ERRORS
    eNOTMIPLEMENTED = vbObjectError + 512
    eXMLMISSINGELEMENT
    eINVALIDCUSTOMERROLE
    eNOADDRESS
    eINVALIDPARAMETER
    eINVALIDDATETIMEFORMAT
    eXMLINVALIDATTTRIBUTEVALUE
    eXMLINVALIDATTTRIBUTE
    eRECORDNOTFOUND
End Enum

