'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace webreference_rpc
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AlphaPlusSoapRpcSoap", [Namespace]:="http://marlborough-stirling.com/WebServices/AlphaPlus")>  _
    Public Class AlphaPlusSoapRpc
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("WebServiceTestHarness.webreference_rpc.AlphaPlusSoapRpc")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/AlphaPlusWebService/AlphaPlusSoapRpc.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://marlborough-stirling.com/WebServices/AlphaPlus/ACERequest", RequestNamespace:="http://marlborough-stirling.com/WebServices/AlphaPlus", ResponseNamespace:="http://marlborough-stirling.com/WebServices/AlphaPlus")>  _
        Public Function ACERequest(ByVal vstrRequest As String) As String
            Dim results() As Object = Me.Invoke("ACERequest", New Object() {vstrRequest})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginACERequest(ByVal vstrRequest As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ACERequest", New Object() {vstrRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndACERequest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
